Enhance messages & chats display
kovdan01/melon pull request #106
Opened 2021-03-10 13:13 UTC by Ctrl-Admiral

Add custom Qt5 delegates to display messages and chats.

For info about works under this PR see #92 Issue.

2021-03-10 17:32 UTC, Ctrl-Admiral commented
Баги:
- [ ] иногда некорректно отображает размер строки в высоту. Предположение: это исправится написанием собственного word-wrapper'a.

Некорректное поведение:
- [ ] невозможно сбросить выбор строки: ни кликом по пустому месту, ни повторным нажатием

2021-03-11 20:08 UTC, kovdan01 requested changes

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    void paint(QPainter* painter, const QStyleOptionViewItem& option,
25 строка по размеру почти такая же, но на одной строке
давай тогда и это без переноса для единообразия

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    std::vector<QString> m_month_names = {tr("Jan"), tr("Feb"), tr("Mar"), tr("Apr"),
а где май? и почему такое "необчное" разбиение (4+3+4) по строкам?

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    QFont m_sender_font     {QStringLiteral("Cantarell"), /*pointSize*/ 9, /*weight*/ QFont::DemiBold};  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
здесь давай не давить, давай честно вынесем это куда-нибудь
в PR по сеттингам сделаем из этого сеттинги, пока что просто сделай какие-нибудь что-нибудь типа

```
struct FontParams
{
    const /*type*/ point_size;
    const /*type*/ weight;
};

static constexpr FontParams m_sender_font_params = { 9, QFont::DemiBold };
// ...

static constexpr QFont m_sender_font{/*...*/, m_sender_font_params.point_size, /*...*/;
```

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    QFont m_sender_font     {QStringLiteral("Cantarell"), /*pointSize*/ 9, /*weight*/ QFont::DemiBold};  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
тут явно будут не лишними static и constexpr (или const, если constexpr компилятор не позволит)

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    constexpr static QColor M_SELECTED_COLOR{30, 30, 90, 50};
здесь можно подписать коментами по аналогии с строками выше

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    constexpr static QColor M_SELECTED_COLOR{30, 30, 90, 50};
кстати, в чем сакральный смысл прозрачности? у нас ничего друг на друга не накладывается, если хочется менее яркий цвет - мб просто изначально делать его таким?

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +    [[nodiscard]] const timestamp_t timestamp() const noexcept
это значение, а не ссылка/указатель, так что конст бессмысленен

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +#include <iostream>
кажется, лишнее

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +#include <QFontMetrics>
давай по алфавиту кутэшные инклуды

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    auto timestamp = message->timestamp();
у нас есть псевдоним timestamp_t, мне кажется есть смысл использовать его

2021-03-11 20:08 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    std::tm timestamp_tm = *std::localtime(&time_tt);
мне кажется нет смысла разыменовывать указатель, сохрани как есть, и обращайся потом к полям через -> вместо точки

2021-03-11 20:46 UTC, Ctrl-Admiral commented on src/client-desktop/include/message_item_delegate.hpp
> +    std::vector<QString> m_month_names = {tr("Jan"), tr("Feb"), tr("Mar"), tr("Apr"),
Потому что май незаслуженно забыт... Исправлено

2021-03-11 20:52 UTC, Ctrl-Admiral commented on src/client-desktop/include/message_item_delegate.hpp
> +    constexpr static QColor M_SELECTED_COLOR{30, 30, 90, 50};
Конкретно здесь прозрачность нужна, потому что на выбранное сообщение прямоугольник накладывается сверху -- все сообщение просто затемняется, по сути. Остальные цвета в основном подобраны лишь бы были хоть какие-то, сейчас буду перекладывать все в конфиг, и поправлю на непрозрачные.

2021-03-11 21:11 UTC, Ctrl-Admiral commented on src/client-desktop/include/message_item_delegate.hpp
> +    QFont m_sender_font     {QStringLiteral("Cantarell"), /*pointSize*/ 9, /*weight*/ QFont::DemiBold};  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
Будет сделано

2021-03-12 18:00 UTC, kovdan01 commented on src/client-desktop/include/message_item_delegate.hpp
> +    constexpr static QColor M_SELECTED_COLOR{30, 30, 90, 50};
Понял, спасибо

2021-03-12 18:17 UTC, kovdan01 requested changes

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +#include <QFont>
давай по алфавиту

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        [[nodiscard]] const FontParams sender_font_params() const
const на возвращаемом значении не имеет смысла, если это не ссылка/указатель

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        friend class UserConfigSingletone;
давай пустую строчку перед private:, а объявление друга - куда-нибудь в начало (можно сразу после public)

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        [[nodiscard]] const int& min_message_width() const
ссылка на инт...

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        [[nodiscard]] const qreal& scale_message_width() const
qreal это что-то маленькое типа double? тогда тоже наверное по значению просто возвращать надо

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        friend class DevelopConfigSingletone;
аналогично тому, что выше - перед private пустая строка, а дружбу перемещаем в самое начало после public

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    auto& dev_config = DevelopConfigSingletone::get_instance();
кажется тут можно и const auto&

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    auto& user_config = UserConfigSingletone::get_instance();
кажется тут можно и const auto&

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +}
закрывающий комент

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    m_sender_font = {user_ap.sender_font_params().family,
DISCLAIMER рюшечек комент

давай попробуем делать так:
```
m_sender_font = 
{
    user_ap.sender_font_params().family,
    user_ap.sender_font_params().size
    user_ap.sender_font_params().weight
};
```
а то скачут эти отступы и имхо не очень красиво

либо привести эти отступы к одному значению, типа

```
m_message_text_font = { user_ap.message_text_font_params().family,
                            user_ap.message_text_font_params().size,
                            user_ap.message_text_font_params().weight };

m_timestamp_font    = { user_ap.timestamp_font_params().family,
                        user_ap.timestamp_font_params().size,
                        user_ap.timestamp_font_params().weight };
```
(фигурные скобочки в таком случае имхо лучше отделять пробелом, лучше видны)

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +        message_background_rect += QMargins( m_base_margin,
а зачем здесь пробел после круглой скобки? вроде у нас так не принято

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    if (!is_previous_same)
все-таки хоть и один оператор внутри, но давай с фигурными скобками - многострочное так или иначе

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    auto* p = qobject_cast<QListView*>(this->parent());
если по этому указателю ничего не меняется, то лучше об этом сообщить, добавив const
или там происходит какое-то изменение?

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    if (num < 10)  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
во, здесь абсолютно правильно подавила! резолвни этот комент, просто хвалю

2021-03-12 18:17 UTC, kovdan01 commented on src/client-desktop/src/message_list_model.cpp
> +bool MessageListModel::has_messages_same_sender_and_time(const int& less_row, const int& bigger_row) const
расскажи, пожалуйста, что это за магия, не очень понял зачем функция эта
и функцию надо как-нибудь переименовать энивей, пока она даже некорректно звучит с точки зрения английского языка

2021-03-12 23:24 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
> +        message_background_rect += QMargins( m_base_margin,
опечатка, размноженная далее. Исправлено

2021-03-12 23:25 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
> +    auto* p = qobject_cast<QListView*>(this->parent());
Да нет, в идеале ничего меняться не должно. Конст добавлен

2021-03-12 23:31 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_list_model.cpp
> +bool MessageListModel::has_messages_same_sender_and_time(const int& less_row, const int& bigger_row) const
Функция нужна, чтобы проверять, у соседнего сообщения (предыдущего или следующего) тот же отправитель? И отправлены ли они примерно в одно время (разница в две минуты)?
Это нужно, чтобы понимать, отрисовывать ли рядом с сообщением иконку и имя отправителя. В последовательности сообщений в рамках одного высказывания от одного человека (а то любят делить свой монолог на короткие отдельные сообщения) каждый раз отрисовка иконки+отправителя смысла не имеет. Если разница во времени между сообщениями одного человека более двух минут (выбрана цифра примерно), будем считать это единым высказыванием, которое нет смысла отделять иконкой.
Ну, то есть сделано аналогично ВК примерно.

Переименовать можно на что-то в духе "check_for_a_single_statement"

2021-03-12 23:39 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
> +    m_sender_font = {user_ap.sender_font_params().family,
Переделала на второй вариант, мне он больше импонирует -- не возникает ассоциации с блоками функций/классов/неймспейсами)

2021-03-13 18:49 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_list_model.cpp
> +bool MessageListModel::has_messages_same_sender_and_time(const int& less_row, const int& bigger_row) const
Переименовано в are_icon_and_sendername_needed

2021-03-15 19:32 UTC, kovdan01 requested changes

2021-03-15 19:32 UTC, kovdan01 commented on src/client-desktop/include/chat_list_model.hpp
> +        RepaintRole = Qt::UserRole + 2,  // NOLINT (readability-identifier-naming)
а почему именно +2, а не +1?

2021-03-15 19:32 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +
Лишняя пустая сртока

2021-03-15 19:32 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        Appearance() = default;
давай сразу после private: поставим конструктор
в "наружнем" классе у тебя так сделано, и имхо оно логичнее

2021-03-15 19:32 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        Appearance() = default;
аналогично: лишняя пустая строка + конструктор давай перенесем

2021-03-15 19:32 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +    [[nodiscard]] bool is_empty() const
почему бы не назвать эту функцию просто empty? в стандартной библиотеке так принято, и, думаю, это кому угодно будет понятно

2021-03-15 19:32 UTC, kovdan01 commented on src/client-desktop/include/message_list_model.hpp
> +        IsPreviousSameSenderAndTimeRole = Qt::UserRole + 2,  // NOLINT (readability-identifier-naming)
давай эту роль переименуем, соответствующую ей функцию ты уже переименовала

2021-03-15 19:34 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_list_model.hpp
> +        RepaintRole = Qt::UserRole + 2,  // NOLINT (readability-identifier-naming)
А потому что там была еще одна роль, которую удалила и не исправила. Исправлю на +1

2021-03-15 20:31 UTC, kovdan01 approved these changes

2021-03-15 20:31 UTC, merged