Add persistent storage
kovdan01/melon pull request #118
Opened 2021-03-23 21:55 UTC by Ctrl-Admiral

2021-03-26 12:44 UTC, Ctrl-Admiral commented
-  Может быть, для единообразия функции remove_from_db() положить в деструкторы? Или наоборот, вытащить код добавления в базу из конструкторов и положить в отдельный функции add_to_db()? Сейчас сделано по аналогии с тем, что на сервере.
- Нужно решить вопрос с обработкой ошибок при выполнении sql-запросов. Просто логировать ошибки? Выдавать критическую ошибку с закрытием программы? Выводить информационное окно?

2021-03-26 17:49 UTC, kovdan01 requested changes

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/chat_item_delegate.hpp
> +#include <db_storage.hpp>
добавила инклуд и больше ничего, оно точно тут вообще нужно?

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    //For Insert
пробел после //

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    [[nodiscard]] std::list<Message>& messages()noexcept
пробел перед noexcept

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    std::list<Message> m_messages = {};
можно и не писать = {}, дефолт-конструктор и так это делает

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +namespace melon::client_desktop
возможно, можно здесь еще сделать неймспейс db внутри, а всякие MessageRAM превратить в ram::Message
имхо, будет довольно логично выглядеть

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    StorageSingletone(const StorageSingletone& root) = delete;
а зачем слово root?

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    chat_handle_t add_chat(const Chat& chat)
а почему по const-ссылке, а не по значению? дальше ты делаешь move, так что тебе тут можно (и даже, кажется, нужно, разве что я чего-то не вкурил) принять по значению
принимая по ссылке, ты делаешь ровно одно копирование (в emplace_back, move тут эффекта не возымеет, работал бы стат анализ - он бы тебе об этом сказал), а принимая по значению, ты делаешь либо два мува, либо одно копирование и один мув - т.е. есть опция вообще "подарить" объект извне и обойтись без копирований

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +
думаю, здесь можно убрать эту строчку

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +Q_DECLARE_METATYPE(std::uint64_t)
напомни, пожалуйста, это для QVariant? а оно из коробки не умеет целочисленные типы?

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +const std::uint64_t MY_USER_ID = 1;
1. давай сделаем псевдоним id_t или что-нибудь такое, в melon::core, он, кстати, уже есть, так что можно использовать melon::core::id_t или притащить using id_t = melon::core::id_t;
2. constexpr
3. здесь вроде сработает и так, но давай для успокоения души inline (определение в хедере все-таки, пусть явно будет слабая связанность, хотя, кажется, для констов оно и так будет)
4. а зачем вообще эти константы? :)

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> -        return m_attachments;
melon::core::Message никакой магии не сделает, тебе явно здесь нужно все проинициализировать, т.е. пойти в БД и сделать нужные селекты
см. по аналогии с https://github.com/kovdan01/melon/blob/develop/src/server/storage/src/storage.cpp#L303

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +    // fr QVariant
for

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +    [[nodiscard]] const QString& text_qstring() const noexcept
правильно понимаю, что ты решила не скрывать своей кустринговой функцией изначальный стд-шный text(), поэтому назвала геттер text_qstring(), а не text()? просто в целом, если тебе стд-шное не нужно, то можно и скрыть его к чертовой матери

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +    void set_text_qstring_RAM(QString text)
а зачем суффикс RAM в названии? класс и так называется MessageRAM

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +        this->set_text_qstring_RAM(text);
кажется, тут нужен мув

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +        std::vector<melon::core::Message::Ptr> answer;
оно точно должно возвращать пустой вектор?

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    if(!qry.prepare(QStringLiteral("INSERT INTO messages"
`if (`

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        std::cout << "Fail preparing inserting message!" << std::endl;
1. раз уж на то пошло, то std::cerr
2. все равно конечно же нет, кинь исключение

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        timestamp_t timestamp, QString text, Status status)
куда-то индент поехал
и, кстати, мы вроде как договаривались сначала text, потом timestamp - ну крч посмотри порядок параметров в core, пусть будет единообразие

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        std::cout << "Fail inserting message!" << std::endl;
аналогично - исключение

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +"                                            WHERE (message_id=")
может, как-то так это отформатировать?
```
QString qry_string = QStringLiteral("SELECT user_id, timestamp, text, status FROM messages "
                                    "WHERE (message_id=") +
                     QString::number(this->message_id()) +
                     // ...
```

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        std::cout << "Fail loading message!" << std::endl;
исключение
ну и else тогда можно будет убрать - в плане его содержимое просто вынести из блока else, сам блок не понадобится

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    QString qry_string = QStringLiteral("UPDATE messages SET text='") + text
что-то нужно сделать с форматированием наподобие предыдущих комментариев

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        std::cout << "Fail updating message text!" << std::endl;
exception

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    if(!qry.prepare(QStringLiteral("INSERT INTO chats"
`if (`

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +int status_to_int(melon::core::Message::Status status)
эта функция не нужна, есть static_cast<int>, и это корректно работает
разве что тебе статик_каст не нравится внешне, ну тогда просто замени содержимое функции - вместо свитча статик_каст
но я бы не извращался и вообще убрал эту функцию

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +melon::core::Message::Status int_to_status(int status)
аналогично

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +    if(!db.open())
`if (`

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +    if (!is_exist)
чтобы уменьшить индент, можно сделать так:
```
if (is_exist)
    return {};
// текущее содержимое if-а
```

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +    bool is_exist = QFile::exists(DB_NAME);
похоже на эльфийский, не могу разобрать
можно, пожалуйста, более натуральное английское название? :) даже просто exists имхо лучше

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +        return error(qApp->translate("OpenDB", "Couldn't open database! %1"));
а возвращать ошибки в виде QString это практика такая и так принято здесь? нельзя ли тут кидать исключения, в текст которых записывать эти ошибки? а то как-то очень по-сишному, возвращаем ошибки как значение функции, потом еще мучиться и их анализировать

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +            std::cout << "Error: " << query.lastError().text().toStdString() << std::endl;
если тебе реально хочется написать что-то, связанное с ошибкой, на экран (в чем я сомневаюсь) - std::cerr

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +        if(!query.exec(QStringLiteral("CREATE TABLE [chats]"
`if (`

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +        if(!query.exec(QStringLiteral("CREATE TABLE [messages]"
`if (`

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    while(qry_for_chats.next())
`while (`

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +        std::cout << "Error while loading chats: " << std::flush;
ты знаешь, что я хочу сказать...

2021-03-26 17:49 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +        while(qry_for_messages.next())
`while (`

2021-03-26 17:59 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_item_delegate.hpp
> +#include <db_storage.hpp>
Неа, не нужно, это артефакт, убираю

2021-03-26 18:09 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.hpp
> +Q_DECLARE_METATYPE(std::uint64_t)
Оно умеет из коробки только int и свои кутэшные) Так что да, это для него

2021-03-26 18:14 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.hpp
> +    StorageSingletone(const StorageSingletone& root) = delete;
Не знаю, это часть твоего когда, я синглтон почти не трогала, а какая разница?

2021-03-26 18:15 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.hpp
> +    chat_handle_t add_chat(const Chat& chat)
Я делала ссылки ради одного: чтобы лишний раз не вызывать конструкторы, которые работают с базой. Но я не знаю, если мы передаем классы по значению, конструктор вызывается или нет?

2021-03-26 18:21 UTC, Ctrl-Admiral commented on src/client-desktop/include/ram_storage.hpp
> +const std::uint64_t MY_USER_ID = 1;
1. Done
2. Done
3. Done
4. В смысле зачем, я ими по всему тексту пользуюсь) Это заглушки, пока мне не приходят реальные вещи. Я не хочу каждый раз создавать сообщения с волшебными чиселками, я хочу просто юзать уже определенные везде константы

2021-03-26 18:26 UTC, Ctrl-Admiral commented on src/client-desktop/include/ram_storage.hpp
> -        return m_attachments;
Не поняла, какие селекты? Ты про какую функцию? set_text_base -- банально замена текста в раме, зачем мне селекты?

2021-03-26 18:29 UTC, Ctrl-Admiral commented on src/client-desktop/include/ram_storage.hpp
> +        std::vector<melon::core::Message::Ptr> answer;
А мне эти две функции задаром не сдались, просто в базовом классе они были определены как чистые виртуальные, и компилятор ругался, чтобы я их явно определила в наследнике

2021-03-26 20:35 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.hpp
> +namespace melon::client_desktop
Будет сделано

2021-03-26 20:36 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.hpp
> +    StorageSingletone(const StorageSingletone& root) = delete;
root убрать

2021-03-26 20:37 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.hpp
> +    chat_handle_t add_chat(const Chat& chat)
Передавать по значению

2021-04-06 09:03 UTC, kovdan01 requested changes

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +#include <db_storage.hpp>
по алфавиту

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    void remove_from_db();
смешались в кучу кони, люди
давай уж эта функция будет последней в списке каждого класса

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    :ram::Domain(hostname, external)
пробел после :

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    :ram::Domain(hostname)
пробел после :

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +melon::core::id_t max_domain_id();
1) ты же определила алиас mc, можно его использовать
2) в ram_storage.hpp ты затащила id_t в melon::client_desktop, так что можно вообще никуда не лезть и тупо писать id_t

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +//For Select
// For

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +void Message::set_from()
почему человеку извне нужно руками звать эту функцию? нельзя ли ее сделать приватной и звать автоматически в том месте, где заполняется user_id?

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    if (this->user_id() == storage.me().user_id())
а проверить домен?

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        m_from = storage.another_user().username();
username@domain

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +void Message::set_is_edit(bool is_edit)
опять же, почему это должно зваться руками? по идее это надо выставлять сразу после update_text или как оно у нас там называется

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        return 0;
1) для INVALID_ID давай заведем соответствующую глобальную константу (см. server storage)
2) это все-таки логичнее сделать -1; я, конечно, понимаю, что в БД индексация зачастую с 0, но все-таки -1 привычнее как INVALID_ID

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        QMessageBox::critical(nullptr, QObject::tr("Error!"), QObject::tr("Error with local database!\nPlease contact us at bugreport@melon.com."));
можно, пожалуйста, оставить только "Error with local database!", а то прямо кринж...

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    exec_and_check_qtsql_query(qry_for_chats, QStringLiteral("SELECT chat_id, domain_id FROM chats"), "Loading chats");
мне не нравится, что логика работы с БД вручную пишется здесь, нужно будет вынести в другое место, но предлагаю в рамках другого PR

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    if (qry.value(0).toInt() > 0)
это значит "если чатов больше нуля"? если так, можно, пожалуйста, добавить коммент, а то кому угодно, не знакомому с QtSql, непонятно

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +    QFontMetrics fm_sender = QFontMetrics(m_sender_font);
в чем сакральный смысл этих свапов?

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
> +        if (message->from() == tr("Me"))
давай лучше уже по-человечески - по user_id и domain_id_user

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/message_list_model.cpp
> +    return ((message1->user_id() == message2->user_id()) && (diff_time.count() < 2));
domain_id_user?

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.ipp
> +[[nodiscard]] inline QString Domain::hostname() const noexcept
noexcept? тут явно надо убрать, конструктор QString-а точно что-нибудь бросает, как минимум bad_alloc

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.ipp
> +[[nodiscard]] inline QString User::username() const noexcept
аналогично

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.ipp
> +[[nodiscard]] inline QString Message::text() const noexcept
аналогично

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +    exec_and_check_qtsql_query(query, QStringLiteral("INSERT INTO domains VALUES (1, 'melon', 0)"), "Insert basic domain");
у тебя имена и id-шники доменов дублируются здесь и в синглтоне
нужно, чтобы они были в одном месте
у тебя же есть insert-конструкторы на Domain и User, может, просто их использовать? а здесь ничего не звать, кроме того, что "инициировать создание" синглтона, внутри которого позовутся нужные консутркторы и сделаются нужные insert-ы

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/ram_storage.hpp
> +namespace ram
не очень мне нравится это название ram - ни о чем не говорит
по сути, эти классы - это наследники базовых, созданные с целью адаптировать их к QString-ам (и, если будет, другим qt-шным типам)
давай сделаем так:
1) ram_storage.* станет entities_qt.*, неймспейс предлагаю назвать detail - есть договоренность, что вещи из detail - это детали реализации, и их трогать не нужно (ведь, судя по всему, нам эти классы нужны только как промежуточные, и не более)
2) db_storage.* станет entities_db.*, классы останутся на месте
3) всякие storage_singletone и тд - предлагаю для них сделать отдельные файлики, скажем, storage.*

если придумаешь более нормальную схему - предлагай, но мне в голову ничего не приходит

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/db_storage.ipp
> +[[nodiscard]] inline Chat::message_handle_t Chat::last_message()
напомни, пожалуйста, а зачем нам эта функция? где она используется? я вот думаю: не должно ли это быть отвесттвенностью вызывающей стороны, проверять на пустоту m_messages

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +        QString qry_str = QStringLiteral("SELECT message_id FROM messages WHERE chat_id=") +QString::number(chat_id)
```
        QString qry_str = QStringLiteral("SELECT message_id FROM messages WHERE chat_id=") + QString::number(chat_id) +
                          QStringLiteral(" and domain_id_chat=") + QString::number(domain_id);
```

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/include/db_storage.hpp
> +    // for QVariant
1) давай уж единообразно - For
2) если оно потом идет как = default - то можно прямо здесь это написать

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    this->set_is_edit(qry.value(5).toBool());  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
запиши себе в следующий PR сделать микро обертку над этим ужасом в виде инкрементов

2021-04-06 09:03 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +    this->set_message_id(max_message_id(this->chat_id(), this->domain_id_chat()) + 1);
у тебя max_xxx_id могут возвращать невалидный id
раз так - надо делать на это проверку
ну либо вместо невалидного id кидать исключение из этих функций

2021-04-06 09:22 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +void Message::set_from()
Можно и нужно, извне она сейчас буквально нигде не вызывается. Перенесено в private

2021-04-06 09:39 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +void Message::set_is_edit(bool is_edit)
Исправлено, перемещено в private

2021-04-06 10:26 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +        return 0;
Решено убрать проверку

2021-04-06 10:33 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +        m_from = storage.another_user().username();
Зачем мне возвращать домен? Эта функция используется только для отображения имени в сообщениях. Если мы хотим у всех сообщений отображать user@domain, то ок. И в любом случае пока заглушка -- потом будем обращаться к базе и вытягивать имя пользователя из нее.

2021-04-06 10:34 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +        QMessageBox::critical(nullptr, QObject::tr("Error!"), QObject::tr("Error with local database!\nPlease contact us at bugreport@melon.com."));
Эту строчку вообще убираю, так как вызов QMessageBox::critical приводит, как обнаружилось, к утечкам памяти. Как нормально выводить пользователю сообщение об ошибке (не только с дб), подумаю в других ПР

2021-04-06 10:38 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +        m_from = storage.another_user().username();
Исправить отображение всех имен на username@domain

2021-04-06 10:46 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    exec_and_check_qtsql_query(qry_for_chats, QStringLiteral("SELECT chat_id, domain_id FROM chats"), "Loading chats");
Ок, добавлено в  #108 .

2021-04-06 10:51 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
> +    QFontMetrics fm_sender = QFontMetrics(m_sender_font);
О, это очень веселые костыли!
Я хочу и QFontMetrics, и QFonts запихнуть как прайват-члены делегата, чтобы не вычислять их каждый раз в painter.
Но! Инициализировать QFonts я могу только в самом конструкторе, потому что там вызываются синглтоны настроек. А значит, и QFontMetrics, которые от них зависят, должны быть инициализированы там же после них.
Проблема: я не могу просто объявить QFontMetrics в классе, а потом в конструкторе их собственно инициализировать, оно должно быть инициализировано на этапе создания. Поэтому в .hpp я им прописываю  фейковую пустую инициализацию (там вроде даже коммент есть), а в конструкторе в .cpp уже подсовываю им настоящие нужные значения.

2021-04-06 11:24 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
> +        if (message->from() == tr("Me"))
Тогда нужно или просто написать волшебные чиселки, которые у нас захардкожены, и сравнивать с ними
Или вызывать синглтон, который хранит всю информацию о нас, и сравнивать с тем. что из него вытащим. Очень не хотелось бы его вызывать, ибо painter воспроизводится _каждый раз_, когда кто-то просто двигает мышкой даже по сообщениям. Мне кажется, дешевле сравнить со строчкой, чем вызывать синглтон
А тут никаких недопониманий быть не может: в поле from в Message мы всегда записываем Me, если при конструировании этого Message оказывается, что юзер_ид и домен_ид совпадают с нашими. То есть эта проверка уже была, по сути.

2021-04-06 11:31 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
> +        if (message->from() == tr("Me"))
Исправлено

2021-04-06 11:37 UTC, Ctrl-Admiral commented on src/client-desktop/src/main.cpp
> +    exec_and_check_qtsql_query(query, QStringLiteral("INSERT INTO domains VALUES (1, 'melon', 0)"), "Insert basic domain");
Просто тогда при зове программы у нас может получиться такая ситуация: в базе уже с прошлого раза лежат засунутые туда значения, а сейчас мы снова конструируем синглтон, и пытаемся вновь вставить в базу эти значения. Нужно будет обрабатывать этот случай, проверять, есть ли что-то уже. Это несколько проблематично, ибо конструкторы юзеров и домена зовутся уже в .hpp, а не прописываются отдельно, где можно будет сделать проверку и в зависимости от нее позвать нужный конструктор селекта или инзерта

Ну и плюс так как это все равно вещи временные и захардкоженные

2021-04-06 12:01 UTC, kovdan01 commented on src/client-desktop/src/db_storage.cpp
> +        QMessageBox::critical(nullptr, QObject::tr("Error!"), QObject::tr("Error with local database!\nPlease contact us at bugreport@melon.com."));
хорошо

2021-04-06 12:02 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.ipp
> +[[nodiscard]] inline Chat::message_handle_t Chat::last_message()
Эта функция используется только в делегате чатов. Я так достаю последнее сообщение, чтобы отобразить его превью.  Чтобы не вызывать сначала всеее сообщения, а потом из них доставать послеееднее, просто такая обертка для удобства

2021-04-06 12:14 UTC, Ctrl-Admiral commented on src/client-desktop/include/ram_storage.hpp
> +namespace ram
Мне не нравится одно: дикое размножение файликов. Может, хотя бы синглтоны в один засунуть?  И будет такой storage_singletone.*.

2021-04-06 12:15 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +    this->set_is_edit(qry.value(5).toBool());  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
Добавлено в #108 .

2021-04-06 12:16 UTC, Ctrl-Admiral commented on src/client-desktop/src/db_storage.cpp
> +    this->set_message_id(max_message_id(this->chat_id(), this->domain_id_chat()) + 1);
невалидный не возвращают, решено в комментах выше

2021-04-06 15:12 UTC, Ctrl-Admiral commented on src/client-desktop/include/db_storage.ipp
> +[[nodiscard]] inline Chat::message_handle_t Chat::last_message()
Проверка внутри функции на пустоту заменена на assert. Функция должна вызываться только после проверки вызывающей стороной на пустоту чата

2021-04-06 15:45 UTC, Ctrl-Admiral commented on src/client-desktop/include/ram_storage.hpp
> +namespace ram
Разнесено по файлам, они переименованы

2021-04-06 16:21 UTC, Ctrl-Admiral commented on src/client-desktop/src/main.cpp
> +    exec_and_check_qtsql_query(query, QStringLiteral("INSERT INTO domains VALUES (1, 'melon', 0)"), "Insert basic domain");
Вся логика создания / открытия БД, а также создания этих юзеров и домена перенесена в синглтон.

2021-04-06 22:55 UTC, kovdan01 requested changes

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +#ifndef MELON_CLIENT_DESKTOP_DB_STORAGE_HPP_
имя хедер-гварда

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +#include <entities_qt.hpp>
по алфавиту

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +    QString m_from;
давай разделим пустой строкой данные и функции

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +    [[nodiscard]] bool empty() const;
кажется, можно добавить noexcept - нужно уточнить, является ли noexcept функция, которая вызывается внутри
почти стопудово является, глянь на cppreference

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +#include "entities_db.ipp"
давай добавим пустую строку перед endif

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_qt.hpp
> +#ifndef MELON_CLIENT_DESKTOP_RAM_STORAGE_HPP_
имя хедер гварда

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_qt.hpp
> +
лишняя пустая строка

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_qt.hpp
> +
давай здесь одну пустую строку уберем, а перед endif добавим

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_qt.ipp
> +inline Message::Message(id_t chat_id, id_t domain_id_chat,
куда-то уехало форматирование
один из возможных вариантов:

```
inline Message::Message(id_t chat_id, id_t domain_id_chat, id_t user_id, id_t domain_id_user,
                        const QString& text, timestamp_t timestamp, Message::Status status)
```

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/entities_qt.ipp
> +
лишняя пустая строка

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/storage_singletones.hpp
> +    {
один хер у нас уже есть ipp - давай туда же эти функции и поместим

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/storage_singletones.hpp
> +    ~StorageSingletone() = default;
деструктор можно не прописывать явно

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/storage_singletones.hpp
> +    ~DBNameSingletone() = default;
деструктор можно не прописывать явно

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/storage_singletones.hpp
> +#include "storage_singletones.ipp"
думаю, включение ipp - это последнее, что должно быть, так что давай сначала q_declare_blablabla, потом это

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/include/storage_singletones.hpp
> +#endif // MELON_CLIENT_DESKTOP_STORAGE_SINGLETONES_HPP_
два пробела

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/chat_item_delegate.cpp
> +    QFontMetrics fm_chat_name = QFontMetrics(m_chat_name_font);
мы же договорились жить без свопов...

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/chat_item_delegate.cpp
> +    if (tm.tm_year != tm_now.tm_year)
больше одной строки (даже если один оператор) - в фигурные скобки

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/chat_item_delegate.cpp
> +    if (sender == tr("Me"))
давай проверять по-человечески через user_id+domain_id

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +        if (message_text != m_pre_edit_message)
а что это за хитрая логика добавилась?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +                        storage.me().user_id(), storage.my_domain().domain_id(),
почему `storage.my_domain().domain_id()` а не что-то типа `storage.me().domain_id()`?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +#include <iostream>
этот хедер здесь нужен?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +melon::core::id_t max_domain_id();
уже писал - зачем писать неймспейсы, если и так мы эти вещи сюда притащили?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +Message::Message(id_t chat_id, id_t domain_id_chat,
мне кажется, можно все id-шники на одну строку, а то больно они короткие по сравнению с 3-ей

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +    if (this->user_id() == storage.me().user_id() && this->domain_id_user() == storage.me().domain_id())
если в else есть фигурные скобки - то и в if должны быть

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +        m_from = storage.another_user().username()  + QStringLiteral("@") + storage.my_domain().hostname();
1) лишний пробел после username()
2) давай уж для приличия storage.another_user.domain.hostname или как-то так
вообще, кажется, напрямую звать домен из синглтона нигде пока не нужно

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +
давай одну пустую строку уберем

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +    auto domain_id = domain_id_qvar.value<id_t>();
почему бы не написать сразу return blablabla?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +    auto user_id = user_id_qvar.value<id_t>();
аналогично

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +    auto msg_id = msg_id_qvar.value<id_t>();
аналогично

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +    auto chat_id = chat_id_qvar.value<id_t>();
аналогично

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +#include <QFile>
зачем этот хедер?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +#include <iostream>
этот хедер тут нужен?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
>              return;
если все плохо, то молча выходим? так и надо?

2021-04-06 22:55 UTC, kovdan01 commented on src/client-desktop/src/message_list_model.cpp
> +    return ((message1->user_id() == message2->user_id()) && (message1->domain_id_user() == message2->domain_id_user()) && (diff_time.count() < 2));
оборачивать каждое условие в () здесь избыточно, только читаемости мешает

2021-04-07 19:01 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_item_delegate.cpp
> +    QFontMetrics fm_chat_name = QFontMetrics(m_chat_name_font);
А где свопы-то? Свопов нет, но вот эта фейковая инициализация, к сожалению, остается, иначе оно просто не билдится.

2021-04-07 19:08 UTC, kovdan01 commented on src/client-desktop/src/chat_item_delegate.cpp
> +    QFontMetrics fm_chat_name = QFontMetrics(m_chat_name_font);
я тебе клянусь, что там отображались свопы, когда я писал этот коммент
видимо, гитхаб периодически работает не так, как надо

2021-04-07 19:32 UTC, Ctrl-Admiral commented on src/client-desktop/include/entities_db.hpp
> +    [[nodiscard]] bool empty() const;
Выглядит так, что да 
![image](https://user-images.githubusercontent.com/56734508/113922762-5d686500-97f0-11eb-91ed-5bbed0569563.png)
Как минимум, судя по всей[ статье](https://en.cppreference.com/w/cpp/language/noexcept_spec), ей не с чего _не быть_ noexcept.

2021-04-07 20:27 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +        if (message_text != m_pre_edit_message)
Это сделано, чтобы лишний раз не лезть в базу изменять то, что по факту не было изменено
Когда мы начинаем менять сообщение, я сохраняю текст до изменений в `m_pre_edit_message`. Если изменения были внесены, то есть `message_text != pre_edit_message`, то мы идем через setData и дальше по цепочке все везде менять.
В противном случае мы в этот блок не попадаем и по сути просто выходим из режима редактирования: возвращаем на место кнопочку Receive и т.д.

2021-04-07 20:29 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +                        storage.me().user_id(), storage.my_domain().domain_id(),
Отличный вопрос, нипочему, изменено на `me().domain_id()`

2021-04-07 20:30 UTC, Ctrl-Admiral commented on src/client-desktop/src/entities_db.cpp
> +#include <iostream>
Уже нет) Убран

2021-04-07 20:30 UTC, Ctrl-Admiral commented on src/client-desktop/src/entities_db.cpp
> +melon::core::id_t max_domain_id();
Артефакты старых времен убраны

2021-04-07 20:35 UTC, Ctrl-Admiral commented on src/client-desktop/src/entities_db.cpp
> +        m_from = storage.another_user().username()  + QStringLiteral("@") + storage.my_domain().hostname();
Просто another_user у себя хранит только domain_id. Чтобы достать домен_id, придется залезть в базу и по айдишнику досттать хостнейм. 
Или в даже в классе юзера хранить не просто domain_id, а полноценный экземпляр класса домена.
В кор-классе он просто хранит айдишник домена. Как лучше сделать мне?

2021-04-07 20:38 UTC, Ctrl-Admiral commented on src/client-desktop/src/entities_db.cpp
> +    auto domain_id = domain_id_qvar.value<id_t>();
Артефакты старых времен убраны)

2021-04-07 20:39 UTC, Ctrl-Admiral commented on src/client-desktop/src/main.cpp
> +#include <QFile>
Артефакт старого времени убран

2021-04-07 20:39 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +#include <iostream>
неа

2021-04-07 20:43 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
>              return;
ok -- это маркер, нажал ли пользователь кнопочку Ок. У нас на вылезающем окошке есть только Ок, Отмена и крестик-закрытие. Если нажали не Ок, то по сути да, мы просто выходим, ничего не сделав

2021-04-08 15:02 UTC, kovdan01 requested changes

2021-04-08 15:02 UTC, kovdan01 commented on src/client-desktop/include/entities_qt.ipp
> +inline Domain::Domain (const QString& hostname, bool external)
какие-то странные пробелы перед открывающей круглой скобкой, у нас так не принято

2021-04-08 15:02 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +        if (message_text != m_pre_edit_message)
понял, спасибо

2021-04-08 15:02 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +        return Message(QLatin1String(""));
а нельзя ли просто Message(message_text)? оно же все равно пустое
тогда вообще этот if по идее не нужен

2021-04-08 15:02 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +        m_from = QObject::tr("Me");
а почему здесь QObject::tr, а не QLatinString? это одно и то же? просто до этого ты везде QLatinString юзала

2021-04-08 15:02 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
>              return;
понял, спасибо

2021-04-08 15:02 UTC, kovdan01 commented on src/client-desktop/src/message_item_delegate.cpp
>              icon_color = Qt::darkCyan;
надо будет добавить вообще такую сущность как аватар пользователя (пока что - просто цвет), и вынести в более подобающее место эту логику
в какой-нибудь из следующих PR это

2021-04-08 15:19 UTC, Ctrl-Admiral commented on src/client-desktop/src/entities_db.cpp
> +        m_from = QObject::tr("Me");
tr -- это то, что можно локализовать, по идее. Me, думаю, при отображении мы таки хотим переводить

2021-04-08 15:20 UTC, Ctrl-Admiral commented on src/client-desktop/src/message_item_delegate.cpp
>              icon_color = Qt::darkCyan;
А еще аватар чата, и вообще -- аватар, да. Записала в свой длинный список

2021-04-08 15:24 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +    [[nodiscard]] bool empty() const;
ты не туда смотрела и усложнила себе работу - смотреть надо здесь https://en.cppreference.com/w/cpp/container/list/empty
там явно написано, что noexcept

2021-04-08 15:25 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +        m_from = storage.another_user().username()  + QStringLiteral("@") + storage.my_domain().hostname();
хранить полноценный экземпляр класса домена ТОЧНО плохая идея
добавь просто в домен еще один select-конструктор - по айдишнику
а для юзера, кстати, аналогично селект-конструктор по user_id и domain_id - сейчас у нас username и domain_id
пусть будут оба варианта, в разных местах кода может быть нужно разное

2021-04-08 15:40 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +        return Message(QLatin1String(""));
Крч, по итоге в функции осталась одна строчка) Вроде работает безбажно

2021-04-08 22:55 UTC, Ctrl-Admiral commented on src/client-desktop/src/entities_db.cpp
> +        m_from = storage.another_user().username()  + QStringLiteral("@") + storage.my_domain().hostname();
Добавлены конструкторы в кор-классах + функции-сеттеры

2021-04-09 02:44 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +        m_from = QObject::tr("Me");
хорошо, спасибо

2021-04-10 19:00 UTC, kovdan01 requested changes

2021-04-10 19:00 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +Domain::Domain(id_t id)
кажется, забыли позвать `detail::Domain()`

2021-04-10 19:01 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +        m_from = storage.another_user().username()  + QStringLiteral("@") + storage.my_domain().hostname();
спасибо

2021-04-11 09:27 UTC, kovdan01 approved these changes

2021-04-11 09:38 UTC, merged