Add setter, getter tests
kovdan01/melon pull request #130
Opened 2021-04-10 09:21 UTC by h3ll0kitt1

2021-04-13 19:19 UTC, kovdan01 requested changes

2021-04-13 19:19 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        REQUIRE_NOTHROW(mss::check_if_domain_exists(db, domain1.domain_id()));
можно по аналогии добавить секцию в которой проверять REQUIRE_THROWS (а лучше REQUIRE_THROWS_AS с конкретным типом исключения) на попытку найти несуществующий домен/другую сущность

2021-04-13 19:19 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +    SECTION("Get hostname")
в чем сакральный смысл выносить это в секции? почитай еще раз то, что я писал в нашей переписке про секции и зачем они нужны (а еще лучше - официальную документацию)
тут (как я это вижу) эта и следующая секции не нужны, просто пишем
```
mss::Domain found_domain1(db, domain1.hostname());
REQUIRE(found_domain1.hostname() == "Paul server");
REQUIRE(found_domain1.external() == false);
```
аналогично в других подобных местах

если тебе где-то хочется два раза объявить переменную с одним именем (или просто ограничить область видимости) - для этого можно использовать просто блоки и ограничивать ими области видимости, но именно секции выделять смысла не вижу
условно здесь бы это выглядело (здесь так не надо, но мб в другом месте пригодится):
```
{
    mss::Domain found_domain1(db, domain1.hostname());
    REQUIRE(found_domain1.hostname() == "Paul server");
}
{
    mss::Domain found_domain1(db, domain1.hostname());
    REQUIRE(found_domain1.external() == false);
}
```
секции приводят к тому, что один и тот же код выполняется много раз, и там, где в этом нет реальной необходимости - я не вижу смысл их плодить
во всяком случае, я так это вижу

2021-04-13 19:19 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +    db.execute(R"(ROLLBACK)");
1) эти две строки везде повторяются - нужно куда-нибудь вынести
2) это явно что-то типа работы с ресурсом - сначала ты его "забираешь" (заполняешь БД), потом "отдаешь" (делаешь ролбэк)
если где-то тесты по пути сфейлили - ты до этого ролбэка даже не дойдешь
тут, мне кажется, нужна маленькая RAII-обертка
в конструкторе она будет захватывать ресурс (делать `db.execute(R"(SET autocommit=0)");` и заполнять тестовые данные), в деструкторе - делать ролбэк и коммит
таким образом, что бы ни произошло во время теста - в конце корректно будет уничтожен RAII-объект и он сделает все нужные ролбэки
т.е. нужно сделать что-то типа:

```
class DBTestRAIIWrapper
{
public:
    DBTestRAIIWrapper()
    {
        m_conn.execute(R"(SET autocommit=0)");
    }

    ~DBTestRAIIWrapper()
    {
        try
        {
            m_conn.execute(R"(ROLLBACK)");
            m_conn.execute(R"(COMMIT)");
        }
        catch (...) // деструкторы не должны выбрасывать исключений (по-хорошему мы сюда никогда не зайдем, но перестраховаться не будет лишним
        {
            // log...
        }
    }

    mysql::connection& conn() { return m_conn; }

private:
     mysql::connection m_conn(mss::config_db());
}
```

и далее в теле теста что-то типа
```
TEST_CASE(/*...*/)
{
    DBTestRAIIWrapper db;
    mss::Domain domain1(db.conn(), "Paul server", false);
    mss::Domain found_domain1(db.conn(), domain1.hostname());
    REQUIRE(domain1 == found_domain1);
}
```

2021-04-17 21:18 UTC, h3ll0kitt1 commented on src/server/storage/src/storage_tests.cpp
> +        REQUIRE_NOTHROW(mss::check_if_domain_exists(db, domain1.domain_id()));
добавила  REQUIRE_THROWS пришлось поменять немного `mss::check_if_domain_exists`,  `mss::check_if_chat_exists` - так как тест не проходил и всегда был ненулевой (особенности max).

2021-04-17 21:22 UTC, h3ll0kitt1 commented on src/server/storage/src/storage_tests.cpp
> +    SECTION("Get hostname")
Сократила число секций, возможно надо было сократить еще больше, но мне кажется, что они должны разбиты по группам, например для сообщений это (Select inserted messages, Get functions, Set functions, Test get_messages() for Chat)

2021-04-18 09:17 UTC, kovdan01 requested changes
Разбиение на тест кейсы и секции мне кажется хорошим, но есть другие проблемы - см. коменты

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        REQUIRE_THROWS(mss::check_if_domain_exists(db.conn(), mc::INVALID_ID));
нужно ловить конкретное исключение по типу - REQUIRE_THROWS_AS

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        REQUIRE_THROWS(mss::Domain{db.conn(), "not_valid_hostname"});
аналогично

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        mss::Domain found_domain1(db.conn(), domain1.hostname());
у нас в core в дополнение к select-конструктору по хостнейму добавился select-конструктор по id, т.к. может быть ситуация, где известен id, и тогда зачем hostname (см. https://github.com/kovdan01/melon/blob/develop/src/core/include/melon/core/entities.hpp#L45)
нужно дописать соответствующий конструктор в storage, и тестить оба варианта
то же самое относится и к юзеру - там добавился конструктор по айдишнику (https://github.com/kovdan01/melon/blob/develop/src/core/include/melon/core/entities.hpp#L94)

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        REQUIRE_NOTHROW(mss::check_if_domain_exists(db.conn(), domain1.domain_id()));
и, соответсвенно, следует сделать перегрузку функций check_if_domain_exists по hostname вместо id

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +    SECTION("Get functions")
по-моему по-русски это называется Getters, а не Get functions

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        mss::Domain found_domain1(db.conn(), domain1.hostname());
если здесь тестируются именно геттеры - не вижу смысла создавать новый экземпляр домена
можно же использовать просто domain1 в следующих двух строках

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        mss::Domain found_domain1(db.conn(), domain1.hostname());
аналогично - я не понял, зачем делать новый экземпляр домена

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +        REQUIRE_THROWS(mss::Domain{db.conn(), found_domain1.hostname()});
REQUIRE_THROWS_AS

2021-04-18 09:17 UTC, kovdan01 commented on src/server/storage/src/storage_tests.cpp
> +TEST_CASE("Test users", "[storage service]")
все, что было сказано про домены - применимо и к другим тест кейсам

2021-04-19 10:16 UTC, h3ll0kitt1 commented on src/server/storage/src/storage_tests.cpp
> +        mss::Domain found_domain1(db.conn(), domain1.hostname());
добавила

2021-04-19 10:36 UTC, h3ll0kitt1 commented on src/server/storage/src/storage_tests.cpp
> +        mss::Domain found_domain1(db.conn(), domain1.hostname());
исправила для всех entity

2021-05-02 11:17 UTC, kovdan01 approved these changes

2021-05-02 11:17 UTC, merged