Add save/load settings
kovdan01/melon pull request #137
Opened 2021-04-19 17:58 UTC by Ctrl-Admiral

2021-05-06 09:05 UTC, kovdan01 requested changes

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +// For Log
я думаю, и так понятно, что boost/log это for log...

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        [[nodiscard]] FontParams sender_font_params() const;
не лучше ли возвращать подобные нетривиальные объекты (и вообще все, что тяжелее 16 байт) как `const FontParams&`?

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/config.hpp
> +        [[nodiscard]] QString font_family() const;
аналогично

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/message_list_model.hpp
>          MessageTextRole = Qt::UserRole + 0,  // NOLINT (readability-identifier-naming)
если есть желание сделать немного красивее - можно NOLINT на один уровень отодвинуть
типа
```
MessageTimestampRole = Qt::UserRole + 1,            // NOLINT (readability-identifier-naming)
AreIconAndSendernameNeededRole = Qt::UserRole + 2,  // NOLINT (readability-identifier-naming)
```

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/settings_dialog.hpp
> +#ifndef SETTINGS_DIALOG_HPP
именование макроса (+ не забудь про комент после endif)

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/settings_dialog.hpp
> +    QSet<QWidget* > m_visited_tabs;
`QSet<QWidget*>`

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/storage_singletones.hpp
>      [[nodiscard]] QString db_name();
здесь, наверное, тоже нужны const-ссылки

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +// For Log
аналогично - думаю, и так понятно :)

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +    save_settings_to_yaml();
а зачем при получении сообщения сохранять настройки?

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +        m_chat_name_font_params.size = 8;  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
аналогично - можно хотя бы немного сгладить эти суппрессы, выведя их на один уровень

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +    BOOST_LOG_TRIVIAL(info) << "In config chatlist size is " << static_cast<int>(m_message_font_size);
если эти логи хочется оставить (я не уверен, нужны ли они вообще или это чисто дебажная вещь была), то предлагаю две вещи
1) как-то переделать сообщение, скажем, "Set font size in chatlist config to XXX"
2) можно наверное написать микроперегрузку operator<< для FonatSize и выводить нормально прямо слова SMALL, BIG или как душе угодно

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +    auto parsed_level_categories = meco::yaml_conf::parse_one_level_down(conf_file, required_parameters.begin(), required_parameters.end());
`meco` - улыбнуло :)
в других местах мы обычно пишем mc, но мне не принципиально, просто забавно звучит

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/entities_db.cpp
> +// For Log
ты уже знаешь, что я хочу сказать

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +    QString m_full_name;
а в чем проблема каждый раз в геттере `full_name` конструировать его, а не хранить? большой перформанс-проблемы я в этом не вижу, зато лишних сущностей станет меньше и код будет лаконичнее (мембер `m_full_name` и сеттер на него отпадут за ненадобностью)

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +// For Log
ооооо (моя боборона)

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +using user_conf_ap = melon::client_desktop::UserConfigSingletone::Appearance;
а что с индентами и в целом с кодстайлом? понимаю, что копипастилось, но надо привести к нормальному виду

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +    auto& storage = StorageNameSingletone::get_instance();
я бы следующие три строки превратил в две:
```
std::string settings_filename = StorageNameSingletone::get_instance().user_settings_file_name();
std::ofstream settings_file(settings_filename);
```

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +    //Appearance
обычно мы ставим пробел после // - давай и здесь

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +    app.set_chat_name_font_params({QStringLiteral("Cantarell"), 9, QFont::DemiBold});  // NOLINT (cppcoreguidelines-avoid-magic-numbers)
аналогично - можно комментарии вывести на один урвень

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +            throw std::runtime_error("Parsing logic failure");  // Something went really wrong, let's throw an exception...
1) exception в любом случае должен быть melon-овский
2) не подойдет ли тут по смыслу `meco::yaml_conf::ExtraParamsException`?

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +        else
аналогично + лишняя пустая строка

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +        else
1) если везде ставишь пустые строки - поставь и перед else
2) вообще мы по кодстайлу ставим {} во всех ветках if/else, если они есть хотя бы в одной, но если оставишь пустые строки - наверное, и так сойдет

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +            throw std::runtime_error("Parsing logic failure");  // Something went really wrong, let's throw an exception...
аналогично - exception должен быть наш

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/settings_dialog.cpp
> +            auto* white_check_box = tab->findChild<QCheckBox* >(QStringLiteral("RemoveWhiteCheckBox"));
`findChild<QCheckBox*>`

2021-05-06 09:05 UTC, kovdan01 commented on src/client-desktop/src/settings_dialog.cpp
> +void SettingsDialog::current_tab_changed(int)
а что сюда прилетает в качестве параметра и почему мы его игнорируем?

2021-05-11 11:58 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +    auto parsed_level_categories = meco::yaml_conf::parse_one_level_down(conf_file, required_parameters.begin(), required_parameters.end());
Из-за забавности и сделано :) Пусть будет)

2021-05-12 22:59 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +    save_settings_to_yaml();
Низачем, артефакт дебажных времен

2021-05-12 23:01 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +    BOOST_LOG_TRIVIAL(info) << "In config chatlist size is " << static_cast<int>(m_message_font_size);
Пожалуй, оставлять не хочется. Верну, если внезапно обнаружатся проблемы

2021-05-12 23:06 UTC, Ctrl-Admiral commented on src/client-desktop/include/entities_db.hpp
> +    QString m_full_name;
Можно я тогда буду возвращать просто QString, а не конст ссылку? Иначе сыпятся ворнинги

2021-05-12 23:09 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +using user_conf_ap = melon::client_desktop::UserConfigSingletone::Appearance;
Вроде поправила

2021-05-12 23:14 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +            throw std::runtime_error("Parsing logic failure");  // Something went really wrong, let's throw an exception...
Ну, в принципе натянуть на глобус можно. Но здесь могут быть и всякие опечатки в именах параметров, а не только лишние параметры. Или просто что-то существенно не так пошло. Могу сделать какой-нибудь общий ParsingYamlException

2021-05-12 23:14 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +            throw std::runtime_error("Parsing logic failure");  // Something went really wrong, let's throw an exception...
А еще это копипаста откуда-то из ядрового кода, так что наверное и там надо менять

2021-05-12 23:15 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +        else
+ пустая строка, выглядит нормально

2021-05-12 23:19 UTC, Ctrl-Admiral commented on src/client-desktop/src/settings_dialog.cpp
> +void SettingsDialog::current_tab_changed(int)
Сюда прилетает индекс текущего таба. Так как мы вызываем внутри currentWidget и получаем указатель на него, нам этот индекс без надобности

2021-05-14 19:35 UTC, kovdan01 commented on src/client-desktop/include/entities_db.hpp
> +    QString m_full_name;
не можно, а нужно
ибо конст-ссылку на что? на временный объект, который моментально станет невалидным?

2021-05-14 19:38 UTC, kovdan01 commented on src/client-desktop/src/config.cpp
> +            throw std::runtime_error("Parsing logic failure");  // Something went really wrong, let's throw an exception...
опечатку от лишнего параметра не отличить, можно просто переименовать ExtraParamsException в UnknownParamException и выкидывать его
или я чего-то не понимаю?
в КРАЙНЕМ случае выкидывай просто melon::Exception, хотя по-моему тут вполне отлично смотрятся ямловские

2021-05-14 19:40 UTC, kovdan01 commented on src/client-desktop/src/settings_dialog.cpp
> +void SettingsDialog::current_tab_changed(int)
я не уверен что это нормально, но пусть будет так, чтоб быстрее закрыть PR
единственное - сделай тогда что-то типа (чтоб было видно что это за параметр) + в описании в хедере то же самое (если оно присутствует)
`void SettingsDialog::current_tab_changed(int /*new_tab_index*/)`

2021-05-15 19:14 UTC, Ctrl-Admiral commented on src/client-desktop/src/config.cpp
> +            throw std::runtime_error("Parsing logic failure");  // Something went really wrong, let's throw an exception...
Переименовала Extra в Unknown, выкидываю его

2021-05-17 10:06 UTC, kovdan01 approved these changes

2021-05-17 10:07 UTC, merged