WIP: Files attaching
kovdan01/melon pull request #141
Opened 2021-05-05 14:47 UTC by RomanAnchugov

close #99

2021-05-06 12:21 UTC, kovdan01 requested changes
1) я так полагаю, что в core-либу будет передаваться полное имя файла на файловой системе, и дальше она сама разберётся - так что научись плес доставать полное имя файла (и его класть в сообщение, чтоб было видно прям, что вот такой-то выбран)
2) аттачи это не отдельные сообщения, когда сделан аттач - должна быть возможность писать еще текст и делать другие аттачи
3) если позволяют возможности стадартного диалога выбора файлов на ведре (а вроде позволяют) - хочется чтоб можно было за один заход сразу несколько файлов прикрепить (не нажимая несколько раз на скрепку)
4) после закрытия приложения сохраняются диалоги и сообщения, но если отправлялись аттачи - они не сохраняются
5) по-моему за все время я ни разу не смог установить приложение как апдейт поверх текущего (ошибка инсталляции), только сносить и делать заново
это норма? как оно решится в дальнейшем?

2021-05-12 11:03 UTC, kovdan01 commented
в рамках этого PR доделываем:
1) в core-либу надо передавать полное имя файла на файловой системе, и дальше она сама разберётся - так что научись плес доставать полное имя файла (и его класть в сообщение, чтоб было видно прям, что вот такой-то выбран)
2) аттачи это не отдельные сообщения, когда сделан аттач - должна быть возможность писать еще текст и делать другие аттачи
3) после закрытия приложения сохраняются диалоги и сообщения, но если отправлялись аттачи - они не сохраняются

выбор нескольких файлов - вынес в задачу #148

2021-05-24 15:53 UTC, kovdan01 requested changes
Все ок, но нет возможности отправить сообщение с пустым текстом, если есть аттачи, а хочется такую возможность иметь 
Сделай, пожалуйста, и тогда смёржим

2021-06-03 19:05 UTC, RomanAnchugov commented
> Все ок, но нет возможности отправить сообщение с пустым текстом, если есть аттачи, а хочется такую возможность иметь
> Сделай, пожалуйста, и тогда смёржим

2021-06-04 16:33 UTC, kovdan01 approved these changes

2021-06-04 16:33 UTC, merged