Add first test client
kovdan01/melon pull request #24
Opened 2020-11-30 17:48 UTC by Ctrl-Admiral

Client can not work because of errors

2020-12-02 14:08 UTC, kovdan01 requested changes
Помимо описанного, нужно:

0. Поправить кодстайл
1. Разные диалоги сделать реально разными
2. Научиться рисовать какие-то прямоугольнички-облачка для сообщений
3. Сейчас длинные сообщения инициируют создание горизонтальной прокрутки, нужно чтобы они разделялись на несколько строк

2020-12-02 14:08 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Почему здесь и в других методах такое странное написание имен методов? Это какие-то "волшебные" имена, которые как-то по-особому интерпретируются Qt? Если необходимости в таком именовании нет, то все в `lower_case`

2020-12-02 14:08 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    if (msgText != QLatin1String(""))
Поищи, нет ли какой константы типа `QStringEmpty`

2020-12-02 14:08 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    QListWidgetItem *msgItem = new QListWidgetItem();
Зачем ручное выделение памяти? Почему не `std::unique_ptr`?

2020-12-02 14:08 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    delete item;
Ручное управление памятью - скорее всего легко заменяется на `std::unique_ptr`

2020-12-02 14:08 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    delete item;
Аналогично про память

2020-12-03 18:06 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    QListWidgetItem *msgItem = new QListWidgetItem();
Это особенности Qt. Буквально везде выделение через new

2020-12-03 18:09 UTC, Ctrl-Admiral commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Эти имена создает сам Qt автоматически, сам дописывает функции в код, когда они добавляются через Qt дизайнер. Это такое общее соглашение в Qt, как я понимаю, везде функции пишутся именно так. Но в целом никто не мешает их переименовывать потом вручную. Если необходимо -- буду

2020-12-03 18:24 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Там проблема в том, что если часть с именем объекта можно изменить, просто заменив имя объекта в Qt Designer (в данном случае `add_chat` вместо `AddChat`), то часть типа `itemDoubleClicked` так и останется в camel-case-е (я же правильно понимаю, что это волшебные суффиксы qt-овские?)

2020-12-03 18:29 UTC, Ctrl-Admiral commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Пока что я это вижу именно так, да, но уверена, что если писать все вручную, а не надеяться на автокод кутэ, можно прописать любое имя функции. То есть эта функция каким-то образом привязана к определенному ивенту, и это гарантированно можно сделать руками. Но пока что я так не делала.

2020-12-03 18:29 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Нашел вот такую статью про сигналы и слоты: https://doc.qt.io/qt-5/signalsandslots.html. Кажется, это имеет к тому отношение, и кажется, все-таки есть возможность выбирать произвольное имя функции (но это неточно). Даже если для этого придется писать какой-то код ручками, ничего страшного, зато явно будет в коде прописана связь, без волшебных имен.

В крайнем случае я просто отключу диагностику на `lower_case` в именах функций, но не хочется идти на этот шаг

2020-12-03 18:54 UTC, Ctrl-Admiral commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Да, это вот ровно оно. Хорошо, я попробую переписать через connect, видимо, по-другому пока никак

2020-12-05 22:06 UTC, Ctrl-Admiral commented on src/client-desktop/include/main_window.hpp
> +    QScopedPointer<Ui::MainWindow> m_ui;
В Qt используется специальный QScopedPointer

2020-12-07 06:50 UTC, kovdan01 requested changes
По сути пока не смотрел, выкатил замечания по стилю. Основное - миллиард лишних NOLINT в коде. Они сделаны НЕ для того, чтобы пихать их где попало, а чтобы подавлять false-positive ворнинги. Еще раз: НЕ все подряд ворнинги. Зачем вообще стат. анализ, если все ворнинги ты подавляешь? (заодно засоряя код)

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/CMakeLists.txt.user
> +<?xml version="1.0" encoding="UTF-8"?>
Этого файла быть в репозитории не должно

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +#ifndef MELON_CLIENT_DESKTOP_CHAT_WIDGET_H
`MELON_CLIENT_DESKTOP_CHAT_WIDGET_HPP_`

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +namespace Ui    // NOLINT (readability-identifier-naming)
ИМХО в данном случае такие гигантские отступы перед комментариями только мешают, давай по классике два пробела

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +}               // NOLINT (llvm-namespace-comment)
Убери NOLINT, тут-то можно и поправить ворнинг

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> -
Это разные группы хедеров (автогенеренные, библиотечные, стандартные), между ними пустая строка по кодстайлу, верни на родину

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +namespace Ui    // NOLINT (readability-identifier-naming)
Аналогично тому, что писал ранее

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +}               // NOLINT (llvm-namespace-comment)
Аналогично

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +    QScopedPointer<Ui::MainWindow> m_ui;    // NOLINT (modernize-use-default-member-init)
Ты как-то переусердствуешь с NOLINT, они созданы не для того, чтобы все подряд подавлять, а чтобы с false-positive бороться. Убирай здесь NOLINT и фикси ворнинг

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +        QListWidgetItem *msg_item = new QListWidgetItem(); // NOLINT (modernize-use-auto)
Опять зачем NOLINT?

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +    QListWidgetItem *msgItem = new QListWidgetItem();    // NOLINT (modernize-use-auto)
Аналогично

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +} //namespace melon::client_desktop
`}  // namespace melon::client_desktop`

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> -
Аналогично

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/src/main.cpp
> +    return application.exec();   // NOLINT (readability-static-accessed-through-instance)
В чем проблема с вызовом return `QApplication::exec();`, зачем менять? Там статическая функция. И опять же NOLINT

2020-12-07 06:50 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +#include <QInputDialog>
Пустая строка нужна

2020-12-07 07:12 UTC, kovdan01 requested changes

2020-12-07 07:12 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +ChatWidget::ChatWidget(QWidget *parent) :
не по кодстайлу:
1) пробелы с указателем
2) `:` и `,`
```
ChatWidget::ChatWidget(QWidget* parent)
    : QWidget{parent},
    , m_ui{new Ui::ChatWidget}
```

2020-12-07 07:12 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    , m_ui{QScopedPointer<Ui::MainWindow>()}
Здесь (как я понимаю) создается просто нулевой указатель, и ниже получаем UB при попытке разыменования. Вот что говорит санитайзер (собирайся с ним!!!):
```
/home/kovdan01/Projects/melon/src/client-desktop/src/main_window.cpp:14:11: runtime error: member call on null pointer of type 'Ui_MainWindow'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/kovdan01/Projects/melon/src/client-desktop/src/main_window.cpp:14:11 in 
```

2020-12-07 15:58 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    if (msgText != QLatin1String(""))
Есть у QString метод isEmpty(), сделано

2020-12-07 15:59 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +}               // NOLINT (llvm-namespace-comment)
Done

2020-12-07 16:02 UTC, Ctrl-Admiral commented on src/client-desktop/src/main.cpp
> +    return application.exec();   // NOLINT (readability-static-accessed-through-instance)
`QApplication::exec()` возвращено на родину

2020-12-07 16:04 UTC, kovdan01 requested changes
Комментарии оставлял не на каждый чих, поэтому если в каком-то месте попросил исправить вещь X, то эту же вещь нужно исправить по всему коду

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +} // namespace Ui
два пробела перед комментом

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +#ifndef MELON_CLIENT_DESKTOP_CHAT_WIDGET_HPP
`#ifndef MELON_CLIENT_DESKTOP_CHAT_WIDGET_HPP_`
подчерк в конце

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/include/main_window.hpp
> +    void provide_chat_context_menu(const QPoint &);
`const QPoint &`

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +        //msg_item->setTextAlignment(Qt::AlignRight);
если закомментированный код не нужен - его быть не должно вообще

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +    auto *msg_item = new QListWidgetItem();
`auto* msg_item`

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +#include <QInputDialog>
пустая строка

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    static uint counter = 0;
что за тип `uint`? cppreference такого не знает

2020-12-07 16:04 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    delete chat;
переделай на `QScopedPointer`, или тут по какой-то фундаментальной причине нельзя?

2020-12-07 16:05 UTC, Ctrl-Admiral commented on src/client-desktop/include/main_window.hpp
> +    void on_AddChat_clicked();
Все сделано через connect

2020-12-07 16:06 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +namespace Ui    // NOLINT (readability-identifier-naming)
Done

2020-12-07 16:06 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +ChatWidget::ChatWidget(QWidget *parent) :
Done

2020-12-07 16:06 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    , m_ui{QScopedPointer<Ui::MainWindow>()}
Done

2020-12-07 16:08 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +#ifndef MELON_CLIENT_DESKTOP_CHAT_WIDGET_HPP
Добавить?..

2020-12-07 16:09 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +} // namespace Ui
Done

2020-12-07 16:11 UTC, Ctrl-Admiral commented on src/client-desktop/include/main_window.hpp
> +    void provide_chat_context_menu(const QPoint &);
Исправлено

2020-12-07 16:15 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    static uint counter = 0;
Исправлено на std::uint32_t. Этого должно хватить на количество диалогов

2020-12-07 16:29 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    static uint counter = 0;
по смыслу это количество чего-то, для этого принято использовать `std::size_t`
и почему бы не хранить его как член класса, зачем статическая переменная?

2020-12-07 16:38 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    static uint counter = 0;
Это счетчик того, сколько раз был создан новый чат. Это можно было бы назвать индексом связки "название чата+его виджет в стаке", но при удалении чего-то из середины индексы у созданных позже не изменятся. Поэтому считать это количеством чатов тоже неправильно. Это как-то слабо похоже на какой-то член, характеристику класса, поэтому сделала статической переменной, она ведь нужна только в этой функции и больше нигде

2020-12-07 16:38 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +#include <QInputDialog>
Done

2020-12-07 16:43 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +    static uint counter = 0;
Кажется, есть смысл изменить на обычный int, поскольку далее методы insertWidget и setCerrentRow кушают именно int

2020-12-07 16:46 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +#ifndef MELON_CLIENT_DESKTOP_CHAT_WIDGET_HPP
да, у хедер-гвардов в конце подчерк

2020-12-07 16:47 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    static uint counter = 0;
хорошо, оставь статик переменной в функции и сделай int
в любом случае, это все временно

2020-12-07 17:23 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +    auto *msg_item = new QListWidgetItem();
DOn(ya)

2020-12-07 17:23 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +        //msg_item->setTextAlignment(Qt::AlignRight);
Yes, sir

2020-12-07 17:25 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +#ifndef MELON_CLIENT_DESKTOP_CHAT_WIDGET_HPP
Хорошо

2020-12-07 18:22 UTC, Ctrl-Admiral commented on src/client-desktop/CMakeLists.txt.user
> +<?xml version="1.0" encoding="UTF-8"?>
Удален в репозитории, добавлен .gitignore, чтобы больше не появлялся

2020-12-07 19:54 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +    delete chat;
Пока оставляем так, конкретнее спросим у ПА

2020-12-07 20:05 UTC, kovdan01 approved these changes

2020-12-07 20:06 UTC, merged