Add basic config parsing for discussion
kovdan01/melon pull request #28
Opened 2020-12-01 06:53 UTC by tyyu3

This is not a final solution for parsing configs, but a most basic one

2020-12-01 11:03 UTC, kovdan01 commented on docs/CONFIGURATION.md
> +	  service_kind: server-server
1) Насколько я знаю, в yaml запрещены табы, только пробелы (но это надо уточнить)
2) Даже если разрешены, везде используем пробелы

2020-12-01 11:18 UTC, kovdan01 commented
Нужно исправить CMakeLists.txt
1) Новые исходники не добавлены в CMakeLists.txt
2) find_package для yaml-cpp

2020-12-03 04:25 UTC, tyyu3 commented
[m_config.zip](https://github.com/kovdan01/melon/files/5633654/m_config.zip)

Тестировал, непоследовательно коверкая этот файлик.

2020-12-03 10:11 UTC, kovdan01 requested changes
Ревью в основном в терминах кодстайла, по сути комментариев мало. Общее
1) если я прокомментировал X как проблему в каком-то месте, то аналогичную проблему надо поправить везде
2) пример использования из auth надо куда-нибудь перетащить, потому что там будет конфликт с PR Алены, выбери любой другой сервис

2020-12-03 10:11 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +    src/yaml_config.cpp
Файл пустой, удалить его и это отсюда убрать

2020-12-03 10:11 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PUBLIC yaml-cpp)
Там нет импортированной цели, только такая?

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/melon_core.hpp
>  #include <melon/core/export.h>
Тут все хедер-онли, макросы `MELON_CORE_EXPORT` не нужны, как и этот инклуд

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +const std::string conf_filename = "m_config.yaml";
Оно компилируется благодаря const, но я все равно предлагаю добавить inline. В случае без const получили бы multiple definition, тут благодаря const компилятор нормально это жует, но для успокоения души хочется видеть inline

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +MELON_CORE_EXPORT std::vector<std::string> check_missing_params(YAML::Node conf, const It req_begin, const It req_end)
Зачем const на передаче параметров по значению? И зачем req_begin/req_end вместо просто begin/end?

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +    for( It it = req_begin; it != req_end; ++it )
Что с пробелами? Пишем так:
`for (It it = req_begin; it != req_end; ++it)`

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +                  std::vector<std::pair<std::string,YAML::Node> >,
Зачем пробелы в `> >`? Современный компилятор прожует и `>>`, а старыми наш код все равно компилироваться не будет

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +                                               It req_begin,
Если параметры в несколько строк, то примерно так должно выглядеть:
```
void foo(int a,
         int b,
         int c)
{
// ...
}
```

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +MELON_CORE_EXPORT std::vector<std::string> check_missing_params(YAML::Node conf, const It req_begin, const It req_end)
`YAML::Node` это владующая вещь, ее содержимое будет тут целиком скопировано? Если да, то const reference

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +        {
По желанию - по нашему кодстайлу тут везде можно убрать фигурные скобки, тогда цикл займет 3 строки вместо 7

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +    for( It it = req_begin; it != req_end; ++it )
indent?

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +    catch (YAML::ParserException &e)
1) const
2) пробел не в том месте

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +                node_res.emplace_back(std::make_pair(*it, parent_node[*it]));
`emplace_back` умеет конструировать на месте, поэтому вместо результата `make_pair` можно просто передать аргументы, которые сейчас идут в него (т.е. просто убрать вызов `make_pair`)

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +    std::vector<std::pair<std::string, YAML::Node> > node_res = {};
Вектор и так по умолчанию пустой, зачем это?

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +/*enum class Services // supported service types
Если не нужно - то надо убрать, в крайнем случае системой контроля версий восстановишь

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +#endif // MELON_CORE_YAML_CONFIG_HPP_
Два пробела перед комментарием

2020-12-03 10:11 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +//  Returns two pairs:
1) после `//` нужен только один пробел; два ставим перед, если это комментарий внутри строки, типа:
 `int a;  // comment`
2) раз уж пошла такая пьянка с документацией, то давай в формате doxygen

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    if(missing_params.size())
Числа на неравенство нулю проверяем по-человечески через == и !=, условия подобного рода это для bool и подобных вещей

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        std::cout<<"[error]:\tsome " << where << " params are missing!\n";
пробелы

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    const std::unordered_set<std::string> required_parameters = {"networking","locations","sasl-policy","password"};
1) возможно, не хватает static
2) предлагаю сделать определение в виде блока для большей читаемости, типа
```
set<T> s = 
{
    v1,
    v2,
    v3,
}
```

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +
с пустыми строками тут явно переборщил

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    for( auto [title, node] : parsed_level_1.first )
`auto&`?

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            for( size_t i = 0; i < node.size(); ++i )
1) `std::size_t`
2) еще не разобрался, что такое node, но судя по контексту range-based for тут явно применить можно

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            for( auto [title, node] : parsed_level_2.first )
Уже есть node на более верхнем уровне. Тут будет работать скрытие имен, все скомпилируется и даже сделает то, что ты захочешь, но не надо так делать, придумай другое имя, это не очень прозрачно для читателя

2020-12-03 10:11 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <yaml-cpp/yaml.h>
Порядок хедеров:
1) парный к cpp
2) собственные
3) third-party
4) системные (типа unistd.h)
5) стандартные

Внутри каждой группы сортировка по алфавиту, между всеми группами, кроме 1 и 2, пустая строка

2020-12-03 10:18 UTC, tyyu3 commented on src/core/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PUBLIC yaml-cpp)
Только такая

2020-12-03 11:37 UTC, tyyu3 commented on src/core/CMakeLists.txt
> +    src/yaml_config.cpp
Согласен, done

2020-12-03 11:40 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    if(missing_params.size())
А вообще здесь напрашивается вызов `empty()`

2020-12-03 11:41 UTC, tyyu3 commented on src/core/include/melon_core.hpp
>  #include <melon/core/export.h>
done

2020-12-03 11:45 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +const std::string conf_filename = "m_config.yaml";
done

2020-12-03 11:50 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +    const std::unordered_set<std::string> required_parameters = {"networking","locations","sasl-policy","password"};
1. Добавил. Мало ли мы захотим несколько раз парсить конфиги
2. done

2020-12-03 12:21 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +
done: везде убрал лишние пустые строки.

2020-12-03 12:28 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +                  std::vector<std::pair<std::string,YAML::Node> >,
done, логично

2020-12-03 13:10 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            for( size_t i = 0; i < node.size(); ++i )
Заменил на range-based.

2020-12-03 13:13 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +MELON_CORE_EXPORT std::vector<std::string> check_missing_params(YAML::Node conf, const It req_begin, const It req_end)
const лишний. Заменил на человеческие begin/end

2020-12-03 13:19 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +    catch (YAML::ParserException &e)
done & done

2020-12-03 13:21 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +                node_res.emplace_back(std::make_pair(*it, parent_node[*it]));
done

2020-12-03 13:27 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +        {
done здесь, и в еще одном месте

2020-12-03 13:29 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +    for( It it = req_begin; it != req_end; ++it )
Поправил

2020-12-03 13:30 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +    std::vector<std::pair<std::string, YAML::Node> > node_res = {};
Не нужно, поправил

2020-12-03 13:36 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +                                               It req_begin,
done

2020-12-03 13:37 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +#endif // MELON_CORE_YAML_CONFIG_HPP_
done, здесь и везде

2020-12-03 14:03 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +//  Returns two pairs:
Исправил, добавил описание в формате doxygen

2020-12-03 14:05 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +    if(missing_params.size())
Заменил на !__.empty()

2020-12-03 14:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +    for( auto [title, node] : parsed_level_1.first )
done

2020-12-03 14:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        std::cout<<"[error]:\tsome " << where << " params are missing!\n";
done

2020-12-03 14:11 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            for( auto [title, node] : parsed_level_2.first )
исправил

2020-12-03 14:18 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +#include <yaml-cpp/yaml.h>
done

2020-12-03 14:24 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +    for( It it = req_begin; it != req_end; ++it )
done

2020-12-03 14:40 UTC, tyyu3 commented on src/core/include/yaml_config.hpp
> +MELON_CORE_EXPORT std::vector<std::string> check_missing_params(YAML::Node conf, const It req_begin, const It req_end)
Сделал const reference

2020-12-03 15:49 UTC, kovdan01 requested changes
Гораздо лучше, с этим уже можно работать
Обрати внимание на комментарии про интерфейс `parse_one_level_down`, там два момента:
1. перегруженность
2. там явно ты хочешь не вектор

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +inline const std::string conf_filename = "m_config.yaml";
1) Эта строчка вроде вообще нигде не используется
2) Если все же нужна, глобальные объекты с префиксом `g_`
3) Если тебе кажется что нужна, подумай еще раз, ТОЧНО ли нужна?

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +std::vector<std::string> check_missing_params(const YAML::Node& conf, const It begin, const It end)
опять `const` на объектах, передающихся по значению
он, конечно, не мешает, но зачем?

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +std::pair<
Очень перегружено, замени пары на какие-нибудь собственные структурки с человекочитаемыми именами полей

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +    std::vector<std::pair<std::string, YAML::Node> > node_res = {};
1. Как же поправил, если нет
2. `> >` - лишний пробел

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +    return std::make_pair(node_res, std::make_pair(missing_res, superfluous_res));
Современный C++ должен компилировать и такой вариант:
`return { node_res, { missing_res, superfluous_res } };`
Попробуй, а вообще, конечно, все эти пары надо убирать, описал выше (впрочем, для собственных тривиальных структур такой трюк тоже работает)

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +}  // namespace melon::core
1. Предлагаю добавить пустую строку перед закрытием неймспейса
2. Кажется, забыл `::yaml_conf` (с clang-tidy какие-то проблемы, он эти проблемы так-то должен видеть, такая диагностика у него есть)

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    "networking",
indent

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    const static std::unordered_set<std::string> required_parameters =
давай лучше `static const`, значения не имеет, просто стилистически

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    "password"
по желанию: у последнего элемента можно писать запятую для единообразия

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    const static std::unordered_set<std::string> required_parameters =
А зачем, к слову, `unordered_set`? Мы это все равно в компайл-тайме задаем, давай `std::vector`, а еще лучше `std::array`

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    auto parsed_level_1 = meco::yaml_conf::parse_one_level_down(conf_file,required_parameters.begin(),required_parameters.end());
пробелы между аргументами при передаче в функцию

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        // Throw exception (or do whatever you want) here...
Уж кинь исключение, если хочешь

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +            auto parsed_level_2 = meco::yaml_conf::parse_one_level_down(node,
тело каждого из этих `if`/`else if` предлагаю в отдельную функцию вынести, очень громоздко и сложно воспринимать

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +                    if (title == "ip")
else if?

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +                    {
Думаю, это то место, где можно убрать фигурные скобки, ибо очень много места занимают

2020-12-03 15:49 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +                }
Тут вообще видится проблема с интерфейсом, который ты предоставляешь
Ты возвращаешь, как я понял, вектор пар "имя параметра" -> "значение параметра". В таком отношении отображения явно напрашивается `unordered_map`

2020-12-03 15:49 UTC, kovdan01 commented on src/core/include/yaml_config.hpp
> +       std::cerr<<"YAML parser error: " << e.what() << std::endl;
пробелы

2020-12-03 17:45 UTC, kovdan01 requested changes

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        std::cout << "[warning]:\tsome " << where << " params are unused!\n";
Я думаю, здесь тоже следует кинуть исключение

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +void parse_locations(const std::string& title, const YAML::Node& node, const std::array<std::string, 4>& required_parameters_locations)
Сделай функцию шаблоном и размер массива передавай как шаблонный параметр

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +                                                                    required_parameters_locations.begin(),
что-то с indent-ами, а вообще псевдоним `namespace meco = melon::core;` я бы из main в глобальную область видимости в этом файле вынес, чтоб не мучиться

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        std::cout << "The " << kind << " service is at " << ip << "\n";
Это, конечно, педантство с моей стороны, но давай символ делать символом, а не строковым литералом (я про `'\n'`)

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    auto parsed_level_2 = melon::core::yaml_conf::parse_one_level_down(node,
аналогично что-то с indent-ами, и упрости себе жизнь псевдонимом неймспейса

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    auto parsed_level_2 = melon::core::yaml_conf::parse_one_level_down(node,
Вообще здесь напрашивается сразу что-то вроде `auto [parsed, abnormal] = ...`, чтоб дальше first и second не звать, да и вообще это читаемее в терминах того, что не нужно лезть в сигнатуру функции и ее документацию и читать, что там за first и second в возвращаемой паре

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        for (std::string& key : superfluous_params)
Кинем исключение?

2020-12-03 17:45 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        if (title == "networking")
Правило следующее: если в цепочке if/else if/else где-то есть фигурные скобки, то они нужны везде
Тут ты можешь в последних двух случаях убрать фигурные скобки, избавившись от `db_loc` (просто использовав временный объект), в else комментарий можно перенести на саму строчку с else. Либо добавляй везде фигурные скобки

2020-12-06 20:20 UTC, tyyu3 commented on src/server/storage/src/main.cpp
> +        std::cout << "The " << kind << " service is at " << ip << "\n";
done

2020-12-06 20:21 UTC, tyyu3 commented on src/server/storage/src/main.cpp
> +    auto parsed_level_2 = melon::core::yaml_conf::parse_one_level_down(node,
done

2020-12-07 07:55 UTC, tyyu3 commented on src/server/storage/src/main.cpp
> +        for (std::string& key : superfluous_params)
done

2020-12-07 07:55 UTC, tyyu3 commented on src/server/storage/src/main.cpp
> +        std::cout << "[warning]:\tsome " << where << " params are unused!\n";
done

2020-12-07 08:07 UTC, tyyu3 commented on src/server/storage/src/main.cpp
> +    auto parsed_level_2 = melon::core::yaml_conf::parse_one_level_down(node,
done

2020-12-07 08:11 UTC, tyyu3 commented on src/server/storage/src/main.cpp
> +        if (title == "networking")
done

2020-12-07 09:04 UTC, kovdan01 requested changes
Беды с наследованием и виртуальными функциями

2020-12-07 09:04 UTC, kovdan01 commented on src/core/include/melon_core.hpp
> +class Exception: public std::exception
пробел
`class Exception : public std::exception`

2020-12-07 09:04 UTC, kovdan01 commented on src/core/include/melon_core.hpp
> +    virtual const char* what() const noexcept{
1. фигурная скобка не там
2. `virtual` убрать, `override` добавить

2020-12-07 09:04 UTC, kovdan01 commented on src/core/include/melon_core.hpp
> +protected:
protected членов класса как правило быть не должно, зачем это тут

2020-12-07 09:04 UTC, kovdan01 commented on src/core/include/melon_core.hpp
> +    virtual const char* what() const noexcept
зачем это дублирование?

2020-12-07 09:04 UTC, kovdan01 commented on src/core/include/melon_core.hpp
> +    MissingParamsException(const std::string& message = "missing params"):msg_(message){}
Аналогично дублирование

2020-12-07 09:10 UTC, kovdan01 commented on src/core/include/melon_core.hpp
> +    MissingParamsException(const std::string& message = "missing params"):msg_(message){}
вообще
1. конструктор такого вида должен быть в САМОМ базовом классе (`melon::exception`)
2. передача строчки должна быть в виде
```
Exception(std::string message)
    : m_message(std::move(message))
{
}
```

2020-12-07 22:05 UTC, kovdan01 requested changes
Смотреть на код приятно, исправь микро замечания по стилю и мёржим

2020-12-07 22:05 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +    include/melon/core.hpp
поменяй местами 28 и 29 строчки

2020-12-07 22:05 UTC, kovdan01 commented on src/core/include/melon/core/exception.hpp
> +class Exception: public melon::Exception
пробел перед двоеточием

2020-12-07 22:05 UTC, kovdan01 commented on src/core/include/melon/core/exception.hpp
> +} // namespace melon::core
два пробела перед комментом

2020-12-07 22:05 UTC, kovdan01 commented on src/core/include/melon/core/exception.hpp
> +#endif // EXCEPTION_HPP
1. два пробела перед комментом
2. имя хедер гварда не то

2020-12-07 22:05 UTC, kovdan01 commented on src/core/include/melon/core/exception.hpp
> +public:
либо везде в наших исключениях добавляй public, либо пусть нигде его не будет, нужно единообразие

2020-12-07 22:05 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <melon/core.hpp>
я думаю тут лучше оставить пустую строку

2020-12-07 22:05 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <melon/core.hpp>
я думаю пустую строчку лучше оставить

2020-12-07 22:08 UTC, tyyu3 commented on src/core/CMakeLists.txt
> +    include/melon/core.hpp
done

2020-12-07 22:11 UTC, tyyu3 commented on src/core/include/melon/core/exception.hpp
> +} // namespace melon::core
done

2020-12-07 22:12 UTC, tyyu3 commented on src/core/include/melon/core/exception.hpp
> +#endif // EXCEPTION_HPP
done

2020-12-07 22:12 UTC, tyyu3 commented on src/core/include/melon/core/exception.hpp
> +public:
done

2020-12-07 22:16 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +#include <melon/core.hpp>
done

2020-12-07 22:23 UTC, tyyu3 commented on src/core/include/melon/core/exception.hpp
> +class Exception: public melon::Exception
done

2020-12-07 22:50 UTC, kovdan01 approved these changes

2020-12-07 22:50 UTC, kovdan01 commented on src/core/include/melon/core/exception.hpp
> +namespace melon::core
Вообще здесь префикс melon:: не нужен, мы же и так внутри

2020-12-07 22:51 UTC, merged