User/h3ll0kitt1/server mech sasl
kovdan01/melon pull request #29
Opened 2020-12-01 07:59 UTC by h3ll0kitt1

Server auth mech

2020-12-01 10:49 UTC, kovdan01 requested changes
Очень много проблем, код написан не на плюсах, а на си по факту, нужно переписывать практически полностью

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <cstring>
Зачем?

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <unistd.h>
Зачем? x2

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#define N_CALLBACKS (16)
1) константы нужно делать нормальными константами, а не дефайнами
2) великолепный антипаттерн "константа размера массива", используй std::array

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +sasl_conn_t *conn = NULL;
1) забыла static?
2) никаких NULL в плюсовом коде, только nullptr

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +const char *mech = "PLAIN";
1) static?
2) const?
2) std::string

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +unsigned len = (unsigned) strlen(mech);
это просто не нужно, когда будет std::string

2020-12-01 10:49 UTC, kovdan01 commented on src/server/server-server/src/main.cpp
> -    melon::core::hello();
Здесь вообще зачем что-то менять было? верни на родину

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    result = sasl_server_init(callbacks, "sample");
Над всеми этими ужасными сишными функциями нужно написать человеческие плюсовые обертки
Дальнейшую логику я не проверяю, пока не будет плюсовых оберток

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +     result = sasl_server_new("someservice", /*"localhost.localdomain."*/ NULL, NULL, NULL, NULL, NULL, 0, &conn);
conn это явно ресурс, sasl_server_new его выделяет, sasl_dispose освобождает, так что RAII

2020-12-01 10:49 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +     result = sasl_server_new("someservice", /*"localhost.localdomain."*/ NULL, NULL, NULL, NULL, NULL, 0, &conn);
опять же nullptr

2020-12-01 11:00 UTC, h3ll0kitt1 commented on src/server/auth/src/main.cpp
> +const char *mech = "PLAIN";
То есть  мне надо будет делать str.c_str(); когда я буду тогда переходить внутри плюсовой обертки к функции из библиотеки?

2020-12-01 11:05 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +const char *mech = "PLAIN";
Да

2020-12-01 11:06 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +const char *mech = "PLAIN";
И вообще по факту это все нужно переписывать, это все будет внутри твоей обертки в каком-то классе типа `SaslServer`, глобальные объекты в данном случае вообще ни к чему

2020-12-06 18:07 UTC, kovdan01 commented
Написал обертки для сервера, нужно написать аналогичные для клиента

2021-01-16 14:46 UTC, kovdan01 commented
See further work in #73

2021-01-16 14:46 UTC, closed without merging