initial
kovdan01/melon pull request #59
Opened 2020-12-07 10:55 UTC by RomanAnchugov

2020-12-11 16:56 UTC, kovdan01 requested changes
Все хорошо, но (за подробностями - см. конкретные комментарии):
* нужно удалить автогенерируемые файлы (в т.ч. бинарный gradle-wrapper.jar)
* копирайты и авторство кода за тобой, но классы явно должны начинаться не с `ru.romananchugov`, а с чего-то типа `org.melon`
* гитигнор предлагаю использовать общепринятый, если нет каких-то особых причин использовать кастомный

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/.gitignore
> -# Built application files
Твой файлик какой-то очень особый? Я брал изначально вот отсюда рекомендованный https://github.com/github/gitignore/blob/master/Android.gitignore, если я не ошибаюсь, твой гитигнор является его подмножеством. В общем, если нет какой-то особой необходимости - предлагаю вернуть на родину как было

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/app/build.gradle
> +        applicationId "ru.romananchugov.melonmessenger"
Здесь давай вернем `org.melon.melon`. Авторство кода твое, копирайты в коде будут твои, но вот эта вещь уже должна быть без чего-то личного

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/app/src/main/java/ru/romananchugov/melonmessenger/presentation/App.kt
> +}
В андроид-разработке принято жить без пустой строки в конце файла? (просто интересно)

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/feature_chats_list/src/main/java/ru/romananchugov/feature_chats_list/di/ChatsListComponent.kt
> +package ru.romananchugov.feature_chats_list.di
Аналогично, вместо `ru.romananchugov` - `org.melon`

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/gradle/wrapper/gradle-wrapper.properties
> +#Sat Dec 05 16:48:39 MSK 2020
этот файл в репозитории лишний (генерируется автоматически)

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/gradlew
> +#!/usr/bin/env sh
аналогично, лишний

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/gradlew.bat
> +@if "%DEBUG%" == "" @echo off
аналогично, лишний

2020-12-11 16:56 UTC, kovdan01 commented on src/client-android/settings.gradle
> +rootProject.name = "MelonMessenger"
Мы точно хотим иметь такое длинное название? Может, лучше как было?

2020-12-30 09:34 UTC, RomanAnchugov commented on src/client-android/app/build.gradle
> +        applicationId "ru.romananchugov.melonmessenger"
done

2020-12-30 09:34 UTC, RomanAnchugov commented on src/client-android/app/src/main/java/ru/romananchugov/melonmessenger/presentation/App.kt
> +}
Нет, ваще не запариваемся на счёт этого

2020-12-30 09:37 UTC, RomanAnchugov commented on src/client-android/feature_chats_list/src/main/java/ru/romananchugov/feature_chats_list/di/ChatsListComponent.kt
> +package ru.romananchugov.feature_chats_list.di
done

2020-12-30 09:37 UTC, RomanAnchugov commented on src/client-android/settings.gradle
> +rootProject.name = "MelonMessenger"
done

2020-12-30 09:42 UTC, RomanAnchugov commented on src/client-android/.gitignore
> -# Built application files
вернул который был

2020-12-30 09:45 UTC, RomanAnchugov commented on src/client-android/gradle/wrapper/gradle-wrapper.properties
> +#Sat Dec 05 16:48:39 MSK 2020
done

2020-12-30 09:46 UTC, RomanAnchugov commented on src/client-android/gradlew
> +#!/usr/bin/env sh
done

2020-12-30 09:46 UTC, RomanAnchugov commented on src/client-android/gradlew.bat
> +@if "%DEBUG%" == "" @echo off
done

2020-12-31 13:57 UTC, merged