Add SASL authentication support for server
kovdan01/melon pull request #73
Opened 2021-01-16 14:40 UTC by tyyu3

2021-02-06 16:01 UTC, kovdan01 requested changes

2021-02-06 16:01 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.hpp
> +    static auto* secret = reinterpret_cast<sasl_secret_t*>(std::malloc(sizeof(sasl_secret_t) + params->password.size() + 1));  // NOLINT cppcoreguidelines-no-malloc
А зачем static?

2021-02-06 21:48 UTC, kovdan01 requested changes
Все норм, кроме того, что описал + дофига лишних (имхо) пустых строк в хедере

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.hpp
> +    std::string_view list_mechanisms();
Можем здесь добавить const или что-то мешает?

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.hpp
> +    size_t m_step_count = 0;
std::

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.hpp
> +    struct StartResult;
1) что-то не вижу где определение этого структа, скажи плес, где оно конкретно
2) а почему определение нельзя сделать здесь?

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.ipp
> +using sasl_res = int;
Это, думаю, вполне можно вынести именно в хедер

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.ipp
> +    static auto* secret = reinterpret_cast<sasl_secret_t*>(std::malloc(sizeof(sasl_secret_t) + params->password.size()));  // NOLINT cppcoreguidelines-no-malloc
Статик убери, а про утечку спросим во вторник

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.ipp
> +sasl_res res = sasl_server_init(nullptr, "localserver");
индент

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.ipp
> +sasl_server_done();
аналогично

2021-02-06 21:48 UTC, kovdan01 commented on src/server/auth/include/sasl_wrapper.ipp
> +    return {.completness = static_cast<AuthCompletness>(res), .response = { clientout, clientout_len }};
1) `{ .completness = static_cast<AuthCompletness>(res), .response = { clientout, clientout_len } }`
2) в функции выше ты прям позвал конструктор явно для возвращаемого значения в аналогичной ситуации, давай единообразие, либо там уберем там конструктор, либо добавим здесь

2021-02-06 21:53 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.hpp
> +    struct StartResult;
1. 168 строка ipp
2. ничего не мешает, а нужно?

2021-02-06 21:53 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.hpp
> +    size_t m_step_count = 0;
done

2021-02-06 23:12 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.hpp
> +    std::string_view list_mechanisms();
можем

2021-02-06 23:12 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.hpp
> +    struct StartResult;
Вытащил определения наверх

2021-02-06 23:23 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.ipp
> +using sasl_res = int;
done

2021-02-06 23:28 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.ipp
> +    static auto* secret = reinterpret_cast<sasl_secret_t*>(std::malloc(sizeof(sasl_secret_t) + params->password.size()));  // NOLINT cppcoreguidelines-no-malloc
done

2021-02-06 23:32 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.hpp
> +    std::string_view list_mechanisms();
done

2021-02-06 23:33 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.ipp
> +sasl_res res = sasl_server_init(nullptr, "localserver");
done

2021-02-06 23:37 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.ipp
> +sasl_server_done();
done

2021-02-06 23:41 UTC, tyyu3 commented on src/server/auth/include/sasl_wrapper.ipp
> +    return {.completness = static_cast<AuthCompletness>(res), .response = { clientout, clientout_len }};
1. done
2. убрал

2021-02-07 14:59 UTC, kovdan01 approved these changes

2021-02-07 15:05 UTC, merged