Add mariadb support
kovdan01/melon pull request #74
Opened 2021-01-28 14:36 UTC by h3ll0kitt1

2021-01-31 18:05 UTC, kovdan01 requested changes
Пока прошелся поверхностно, жду изменений по текущим замечаниям + когда поправлю билд, жду фиксов по ворнингам стат анализаторов

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/CMakeLists.txt
> +include_directories("melondb.h")
`include_directories` и `link_directories` без префикса `target` вообще нигде использовать не надо, то бишь здесь нужно как минимум изменить на `target_include_directories`, а по-хорошему и оно здесь лишнее - автогенеренные файлы должны быть в билд-каталоге, а билд-каталог и так через ntc-cmake подсасывается как каталог для инклудов

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    long userid;
Какой сакральный смысл в `long`?
* точно хочется знаковый тип?
* если хочется 64-битный тип, то `std::uint64_t` (а `long` далеко не везде 64 бит)

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    bool status;
Что это за статус? Если это онлайн-офлайн (да и на деле абсолютно любой статус), то здесь же внутри структуры сделай `enum class` с нужными полями (у тебя будет два пока что, типа `ONLINE` и `OFFLINE`, или что там хотелось)

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    std::vector<std::string> onlineUsersNames;
Неверный case-style для переменных, когда поправлю билд, тебе на стат анализе вылезут ошибки, исправишь

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        onlineUsers.push_back(user);
* Объект `user` можно создавать внутри цикла, благо конструктор там почти тривиальный
* Здесь можно сделать `std::move`
* Вместо `push_back` везде `emplace_back`

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/src/main.cpp
>      try
Если нужен большой try/catch на всю функцию, то можно написать так:
```
int main() try
{
    // ...
}
catch (const ex_type_1& e)
{
    // ...
}
catch (const ex_type_2& e)
{
    // ...
}
```

2021-01-31 18:05 UTC, kovdan01 commented on src/server/storage/src/melondb.h
> +// generated by ./ddl2cpp /home/user/Desktop/melondb.sql /home/user/Projects/melon/src/server/storage/src/melondb.h melon
* Автосгенерированные файлы должны находиться в билд-каталоге
* В репозитории их в любом случае быть не должно

2021-01-31 18:17 UTC, kovdan01 requested changes

2021-01-31 18:17 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +static auto config_melondb()
Вот тут не надо auto...

2021-01-31 18:17 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    auto config = std::make_shared<mysql::connection_config>();
А оно случаем не умеет сразу в конструктор принимать то, что ты дальше ручками указываешь? Мб сразу указать можно?

2021-01-31 18:21 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +struct User
Этот класс хочется видеть в библиотеке core в неймспейсе `melon::core`
И, думаю, можно сделать его сразу прямо классом, а не структом, и по заветам инкапсуляции сделать доступ к полям через геттеры и сеттеры (потом в сеттеры можно и нужно будет запихать обновление БД скажем)

2021-01-31 18:21 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +static std::vector<std::string> OnlineUsersNamesGet(mysql::connection& db)
Описания таких функций можно вынести в хедер в рамках сервиса storage, определения - в парный cpp-шник, т.к. наверное захочется их использовать из многих мест (да и вообще они просто логически связаны), ну и поместить их в неймспейс `melon::server::storage` или даже `melon::server::storage::helpers`

2021-02-06 16:49 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    auto config = std::make_shared<mysql::connection_config>();
Я везде встречала только такой вариант, во всех "официальных" примерах тоже

2021-02-06 16:50 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +static auto config_melondb()
меня на такой длинный std::make_shared<mysql::connection_config> ?

2021-02-06 16:54 UTC, kovdan01 requested changes

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    uint32_t userid;
`std::`
И почему нельзя 64-битный тип? мы ограничиваем количество юзеров 4 миллиардами?

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/CMakeLists.txt
> +set(SQLPP11_)
Зачем?

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    enum status
* `enum class`
* Status (с большой буквы)

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    } stat;
`};`

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    uint64_t messageid;
`std::`

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    enum status
см. User

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        SUCCES
SUCCESS,

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +const auto messages = melon::Messages{};
Вообще почему бы в этих строках не писать типа `const melon::Messages messages;`? Зачем так явно звать дефолт-конструктор и юзать авто?

2021-02-06 16:54 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +        db.execute(R"(CREATE TABLE chats (
Я так понимаю, что схема таблицы задается еще на этапе генерации хедера через питоновский скрипт. Зачем тут ручками прописывать это все? Моментально получим ошибку, когда хедер поменяли, а здесь нет, или наоборот
Должен быть способ автоматически создавать нужные таблицы по тому, что есть в хедере или что-то типа такого

2021-02-06 16:56 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    uint32_t userid;
у нас уникальны в рамках всех серверов ? мы же вроде собирались добавлять делать primary key для всех по двум значениям? userid и serverid ?

2021-02-06 16:59 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +static auto config_melondb()
1) не `std::make_shared<mysql::connection_config>`, а `std::shared_ptr<mysql::connection_config>` (make_shared - функция, которая создает shared_ptr)
2) да, так и писать
авто нужно, чтобы не писать длинное имя типа там, где оно дублируется
тут это сигнатура функции, и авто в сигнатуре функции это совершенно нечитаемо

2021-02-06 17:03 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    auto config = std::make_shared<mysql::connection_config>();
Посмотри его конструкторы, что они умеют принимать

2021-02-07 12:08 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +static auto config_melondb()
```std::shared_ptr<mysql::connection_config> config_melondb();``` изменила

2021-02-07 12:09 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +static std::vector<std::string> OnlineUsersNamesGet(mysql::connection& db)
добавила storage.hpp melon_storage.cpp и namespace ```melon::server::storage```

2021-02-07 12:11 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    uint32_t userid;
изменила на ```std::uint64_t userid;```

2021-02-07 12:11 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +const auto messages = melon::Messages{};
изменила ```const melon::Users g_users;
const melon::Messages g_messages;
const melon::Chats g_chats;```

2021-02-08 14:29 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +struct User
добавила

2021-02-08 14:29 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +        onlineUsers.push_back(user);
изменила

2021-02-08 14:30 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    long userid;
изменила

2021-02-13 16:25 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    bool status;
добавила

2021-02-13 16:25 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    std::vector<std::string> onlineUsersNames;
исправила

2021-02-13 16:26 UTC, h3ll0kitt1 commented on src/server/storage/src/melondb.h
> +// generated by ./ddl2cpp /home/user/Desktop/melondb.sql /home/user/Projects/melon/src/server/storage/src/melondb.h melon
вроде исправила

2021-02-13 16:26 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    enum status
исправила

2021-02-13 16:26 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    } stat;
исправила

2021-02-13 16:27 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    uint64_t messageid;
исправила

2021-02-13 16:27 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    enum status
исправила

2021-02-13 16:27 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +        SUCCES
исправила

2021-02-15 16:57 UTC, kovdan01 requested changes
Файлик  src/server/storage/Readme.md пустой, а хочется видеть ридмишку какую-то
И назови его пожалуйста README.md, по канонам

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    [[nodiscard]] const std::string username() const;
`const std::string&`

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    enum class Status: std::uint8_t
`enum class Status : std::uint8_t`

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +        OFFLINE, ONLINE, CHILL
давай лучше на каждой строке, вот так:
```
OFFLINE,
ONLINE,
CHILL,
```

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    enum class Status: std::uint8_t
1) все аналогично User-у
2) RECEIVED

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    [[nodiscard]] const std::string text() const;
аналогично юзеру

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    [[nodiscard]] const std::chrono::high_resolution_clock::time_point timestamp() const;
конст тут бесполезен, это же не ссылка и не указатель

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    bool m_seen;
1) я не уверен, что seen это должен быть bool, мне кажется эту информацию можно поместить в Status
2) поля прописываются в порядке уменьшения выравнивания, у була выравнивание 1, у последующих timestamp и user_id - по 8, у chat_id - 4; у предыдущего статуса кстати тоже выравнивание 1, так что его нужно в конец

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    [[nodiscard]] std::uint64_t messageid() const;
часть таких имен у тебя идет как `something_id`, часть как `somethingid`
давай сделаем единообразно, предлагаю делать `something_id`

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    std::uint32_t m_chatid;
аналогично про выравнивание

2021-02-15 16:57 UTC, kovdan01 commented on src/core/include/melon/storage_class.hpp
> +    [[nodiscard]] const std::string chatname() const;
аналогично

2021-02-15 16:57 UTC, kovdan01 commented on src/core/src/storage_class.cpp
> +    :m_userid(std::move(userid)), m_username(std::move(username)), m_status(std::move(status))
```
: m_userid(userid)
, m_username(std::move(username))
, m_status(status)
```

2021-02-15 16:57 UTC, kovdan01 commented on src/core/src/storage_class.cpp
> +    :m_username(std::move(username))
`: m_username`

2021-02-15 16:57 UTC, kovdan01 commented on src/core/src/storage_class.cpp
> +[[nodiscard]] User::Status User::status() const
это тривиальные геттеры, их явно хочется видеть inline, так что пропиши их прям в хедере

2021-02-15 16:57 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +namespace mysql = sqlpp::mysql;
в хедере лучше не вводить такие псевдонимы, почти как using namespace получается

2021-02-15 16:57 UTC, kovdan01 commented on src/server/storage/script/ddl2cpp
> +#!/usr/bin/env python
а разве этот файлик здесь нужен? он же с sqlpp11 поставляется, лишняя забота его за собой таскать

2021-02-15 16:57 UTC, kovdan01 commented on src/server/storage/CMakeLists.txt
> +    src/melon_storage.cpp
парный к этому сорцу хедер называется просто storage.hpp, давай и этот назовем storage.cpp, чтоб было ясно все

2021-02-15 20:38 UTC, h3ll0kitt1 commented on src/server/storage/CMakeLists.txt
> +    src/melon_storage.cpp
изменила

2021-02-15 20:39 UTC, h3ll0kitt1 commented on src/server/storage/CMakeLists.txt
> +include_directories("melondb.h")
изменила

2021-02-15 20:40 UTC, h3ll0kitt1 commented on src/core/include/melon/storage_class.hpp
> +    [[nodiscard]] const std::string username() const;
```[[nodiscard]] const std::string& username() const;```

2021-02-23 15:04 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +#include "storage.hpp"
`#include <storage.hpp>`

2021-02-23 15:04 UTC, kovdan01 requested changes
+ дописать readme

2021-03-01 20:12 UTC, kovdan01 approved these changes

2021-03-01 20:22 UTC, merged