Create temp tests for JNI
kovdan01/melon pull request #77
Opened 2021-02-08 11:47 UTC by RomanAnchugov

2021-02-08 14:26 UTC, kovdan01 requested changes
Обязательно нужно поправить ворнинги стат анализов (там есть реальные баги) + по мелочам в основном стилистически оставил коменты

2021-02-08 14:26 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +        include/melon/jni_tests.hpp
куда-то форматирование поехало

2021-02-08 14:26 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +        src/jni_tests.cpp)
тут тоже + скобочка

2021-02-08 14:26 UTC, kovdan01 commented on src/core/include/melon/jni_tests.hpp
> +#ifndef MELON_CORE_JNI_TESTS_HPP
`#ifndef MELON_CORE_JNI_TESTS_HPP_`

2021-02-08 14:26 UTC, kovdan01 commented on src/core/include/melon/jni_tests.hpp
> +#endif //MELON_CORE_JNI_TESTS_HPP
два пробела перед коментом, один пробел после, т.е. будет `#endif  // MELON_CORE_JNI_TESTS_HPP_`

2021-02-08 14:26 UTC, kovdan01 commented on src/core/src/jni_tests.cpp
> +int int_test_sum(int a, int b){
открывающие фигурные скобочки на след строке делаем

2021-02-08 14:26 UTC, kovdan01 commented on src/core/src/jni_tests.cpp
> +    char shit[10] = "poooooook";
1) здесь явно бага, возвращаешь указатель на локальный буфер на стэке, протухнет
2) вроде можно писать `char shit[] = "blabla";`, без указания конкретного количества символов, чтобы не ошибиться случайно

2021-03-02 17:54 UTC, RomanAnchugov commented on src/core/include/melon/jni_tests.hpp
> +#ifndef MELON_CORE_JNI_TESTS_HPP
done

2021-03-02 17:55 UTC, RomanAnchugov commented on src/core/include/melon/jni_tests.hpp
> +#endif //MELON_CORE_JNI_TESTS_HPP
done

2021-03-02 17:55 UTC, RomanAnchugov commented on src/core/src/jni_tests.cpp
> +int int_test_sum(int a, int b){
done

2021-03-02 18:07 UTC, RomanAnchugov commented on src/core/src/jni_tests.cpp
> +    char shit[10] = "poooooook";
дропнул этот метод. Указатели не нужны

2021-03-03 15:51 UTC, kovdan01 requested changes
Я не увидел использования JNI в самом приложении, надо это добавить, т.к. без этого не получится настроить пайплайн - нужно, чтобы JNI-код реально собирался
Предлагаю так: в каждом диалоге новосоздаваемом сейчас есть сообщение "your test" от собеседника, вот давай это сообщение заменим на выхлоп функции `string_test`. Это как раз относительно "сложный" случай со строками будет (а не тупо числа)

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +        hello-jni.cpp)
Давай в таких местах по 4 пробела делать, а не по 8

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <cstring>
вроде этот хедер не нужен

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <iostream>
этот тоже

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <melon/jni_tests.hpp>
собственные хедера в начале, дальше 3rd-party либы, дальше от системы, дальше стандартные, между группами - пустая строка
условно у тебя будет

```
#include <melon/jni_tests.hpp>

#include <jni.h>
```

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +Java_org_melon_jniwrapper_TestWrapper_another(JNIEnv *env, jobject thiz) {
открывающая фигурная скобка - на новой строке

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +    auto str = string_test();
здесь давай явно тип напишем, auto юзаем только там, где иначе нельзя/если есть дублирование типа/для совсем стандартных случаев типа итераторов

2021-03-03 15:51 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +    include/melon/core/jni_tests.hpp
два раза, один нужно убрать
вообще в таких местах сортируем по алфавиту

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <melon/jni_tests.hpp>
этот хедер переехал - melon/core/jni_tests.hpp

2021-03-03 15:51 UTC, kovdan01 commented on src/core/CMakeLists.txt
> +    src/jni_tests.cpp
давай по алфавиту

2021-03-03 15:51 UTC, kovdan01 commented on src/core/include/melon/core/jni_tests.hpp
> +const char* buff_test();
для этой функции нет реализации, давай уберем

2021-03-03 15:51 UTC, kovdan01 commented on src/core/include/melon/core/jni_tests.hpp
> +
отсюда и до #endif нужен namespace melon::core
при закрытии нужно поставить соответствующий комент
т.е.

```
#ifndef MELON_CORE_JNI_TESTS_HPP_
#define MELON_CORE_JNI_TESTS_HPP_

// includes

namespace melon::core
{

// code

}  // namespace melon::core

#endif  // MELON_CORE_JNI_TESTS_HPP_
```

2021-03-03 15:51 UTC, kovdan01 commented on src/core/include/melon/core/jni_tests.hpp
> +#endif  // MELON_CORE_JNI_TESTS_HPP
подчерк в конце забыт

2021-03-03 15:51 UTC, kovdan01 commented on src/core/include/melon/core/jni_tests.hpp
> +#include <string>
Хедеры по алфавиту

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +target_link_libraries(
1. что такое log, оно точно нужно?
2. добавь, пожалуйста, PRIVATE после hello-jni, т.е. условно `target_link_libraries(hello-jni PRIVATE android melon-core)`

2021-03-03 15:51 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +# Include libraries needed for hello-jni lib
Имхо этот комент не нужен, но если очень хочется оставить, то link, а не include

2021-03-03 17:16 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +        hello-jni.cpp)
done

2021-03-03 17:17 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <cstring>
done

2021-03-03 17:17 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <iostream>
done

2021-03-03 17:17 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <melon/jni_tests.hpp>
done

2021-03-03 17:18 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +Java_org_melon_jniwrapper_TestWrapper_another(JNIEnv *env, jobject thiz) {
done

2021-03-03 17:18 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +    auto str = string_test();
done

2021-03-03 17:21 UTC, RomanAnchugov commented on src/core/CMakeLists.txt
> +    include/melon/core/jni_tests.hpp
done

2021-03-03 17:22 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/hello-jni.cpp
> +#include <melon/jni_tests.hpp>
done

2021-03-03 17:22 UTC, RomanAnchugov commented on src/core/CMakeLists.txt
> +    src/jni_tests.cpp
done

2021-03-03 17:23 UTC, RomanAnchugov commented on src/core/include/melon/core/jni_tests.hpp
> +const char* buff_test();
done

2021-03-03 17:25 UTC, RomanAnchugov commented on src/core/include/melon/core/jni_tests.hpp
> +
done

2021-03-03 17:25 UTC, RomanAnchugov commented on src/core/include/melon/core/jni_tests.hpp
> +#endif  // MELON_CORE_JNI_TESTS_HPP
done

2021-03-03 17:26 UTC, RomanAnchugov commented on src/core/include/melon/core/jni_tests.hpp
> +#include <string>
done

2021-03-03 17:26 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +target_link_libraries(
done

2021-03-03 17:26 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +# Include libraries needed for hello-jni lib
done

2021-03-03 17:40 UTC, kovdan01 requested changes

2021-03-03 17:40 UTC, kovdan01 commented on src/core/src/jni_tests.cpp
> +int int_test_sum(int a, int b)
здесь тоже должно быть все в неймспейсе melon::core, иначе это вообще другие функции))

2021-03-03 17:40 UTC, kovdan01 commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +        hello-jni
Здесь тоже по 4 пробела давай

2021-03-03 17:47 UTC, RomanAnchugov commented on src/core/src/jni_tests.cpp
> +int int_test_sum(int a, int b)
done

2021-03-03 17:47 UTC, RomanAnchugov commented on src/client-android/jniwrapper/src/main/cpp/CMakeLists.txt
> +        hello-jni
done

2021-03-03 19:12 UTC, kovdan01 approved these changes

2021-03-03 19:13 UTC, merged