Add creation submenu to class constructor
kovdan01/melon pull request #82
Opened 2021-02-23 13:21 UTC by Ctrl-Admiral

Initial commit for the PR about extending context menu handling

2021-02-23 13:49 UTC, Ctrl-Admiral commented
In work: 
- [ ] override right-click event

2021-02-24 19:58 UTC, Ctrl-Admiral commented
Теперь при вызове контекстного меню _на списке чатов_ (для )  соответствующий чат не становится _выбранным_, но действия меню работают именно для него.

Как бонус: теперь сообщения можно отправить по нажатию на Enter. Соответственно, перенос строки идет по сочетанию клавиш Shift+Enter. Кроме того, при отправке теперь удаляются лишние переносы строки и пробелы в конце и в начале сообщения.

2021-02-25 21:12 UTC, kovdan01 requested changes

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +    bool eventFilter(QObject *object, QEvent *event) override;
нейминг такойСпециально? потому что функция определена в QWidget таким образом и мы ее переопределяем?

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/include/chat_widget.hpp
> +    const QColor m_receive_color = QColor(250, 224, 180, 127);
1) наверное можно `const QColor m_receive_color{ 250, 224, 180, 127 };`
2) наверное можно еще и static, чтоб на все экземпляры класса цвет создавался только один, нет смысла выделять под него место везде

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/src/chat_list_widget.cpp
> +    if(event->button() == Qt::RightButton)
`if (`

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +         m_submenu_sended_messages.popup(m_ui->MsgList->mapToGlobal(pos));
кажется, лишний пробел появился в indent-е

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +#include <QSplitter>
давай по алфавиту отсортируем кьютовские инклуды

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/src/main_window.cpp
> +        //m_ui->ChatPlace->removeWidget(m_chat_widget);
если не нужно - давай удалим

2021-02-25 21:12 UTC, kovdan01 commented on src/client-desktop/src/chat_widget.cpp
> +    , m_submenu_sended_messages(QMenu(this))
вообще ты вроде не брезгуешь синтаксисом через фигурные скобки, так что можно в конструкторах везде его использовать, где компилятором дозволено
для единообразия + это типа современнее (вообще не помню точно какие там плюшки, лучше палсана спросить, но в целом уже сейчас можно везде понапихать фигурных скобок, если религии не противоречит)

2021-02-25 21:21 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +    bool eventFilter(QObject *object, QEvent *event) override;
Да, так и есть. Там еще есть installEventFilter функция, где я включаю этот ивентфильтр для объекта.

2021-02-25 21:24 UTC, Ctrl-Admiral commented on src/client-desktop/include/chat_widget.hpp
> +    const QColor m_receive_color = QColor(250, 224, 180, 127);
Заменено на
```    constexpr static QColor m_receive_color{250, 224, 180, 127};```
(constexpr хотел компилятор, с просто констом не компилил)

2021-02-25 21:25 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_list_widget.cpp
> +    if(event->button() == Qt::RightButton)
Done

2021-02-25 21:29 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +        //m_ui->ChatPlace->removeWidget(m_chat_widget);
Без него работает, но во избежание багов восстановила (сначала убрать виджет из лэйаута, а потом уже удалить).

2021-02-25 21:31 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +         m_submenu_sended_messages.popup(m_ui->MsgList->mapToGlobal(pos));
Исправлено

2021-02-25 21:34 UTC, Ctrl-Admiral commented on src/client-desktop/src/chat_widget.cpp
> +    , m_submenu_sended_messages(QMenu(this))
Скобки впихнуты)

2021-02-25 21:35 UTC, Ctrl-Admiral commented on src/client-desktop/src/main_window.cpp
> +#include <QSplitter>
Отсортировано

2021-02-25 21:58 UTC, kovdan01 approved these changes

2021-02-25 22:03 UTC, merged