User/tyyu3/auth transport
kovdan01/melon pull request #94
Opened 2021-03-06 16:33 UTC by tyyu3

2021-03-11 21:20 UTC, kovdan01 requested changes

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/CMakeLists.txt
> +add_executable(melon-auth-test-client
давай вынесем melon-auth-test-client в отдельную переменную типа TEST_CLIENT_NAME и будем ее использовать

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <boost/multiprecision/cpp_int.hpp>
тут *реально* нужны все эти инклуды?

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +namespace ce
namespace ce - это что-то палсановское
давай палсановское будет в 3rd-party, как либа оно уже вынесено, и там скорее всего оно есть

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            std::string in_buf_, out_buf_;
m_in_buf, m_out_buf

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                    stream_.expires_after(time_limit_);
если переменные с суффиксом _ это что-то приватное, то они должны быть с префиксом m_

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                bl::expressions::stream
куда-то форматирование поехало
вообще настройка boost log выглядит полезной для чего угодно, можно сделать какой-нибудь враппер и вынести в коре

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        if (argc<2||argc>3)
давай без вот этого кастомного разбора cli-опций на палсановских функциях, есть boost program_options, примеры - в любом коде из того, что я тебе кидал

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        ce::ba::io_context ctx{int(threads)};
а почему ты везде обращаешься к boost asio через ce? если хочется сделать алиас ba - давай сделаем свой

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        for(unsigned i=1;i<threads;++i)
форматирование

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    catch(...)
пробел

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +catch(...){
пробел, скобка

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test.cpp
> +
пустые строчки...

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test.cpp
> +    [[maybe_unused]] int x = msa::a();
это нужно?

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test.cpp
> +    msa::Credentials credentials = { .username = "john", .password = "doe" };
давай через cli опции принимать это

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test.cpp
> +#include <sasl_wrapper.hpp>
про что этот файлик? это тест в рамках одного приложения, без транспорта? и, по-моему, он не компилируется вообще ни в рамках чего
можно эту штуку оставить, но тогда сделать третьим executable-ом, видимо

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test.cpp
> +    assert(selected_mechanism == wanted_mechanism);
я думаю, что это должен быть не ассерт, а реальная проверка с реальным выбросом исключения если что-то не так
ибо такая штука может произойти в реальной жизни, и что дальше как говорится
это не предусловие, это просто то, что нужно проверитть

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +      std::cerr << "Usage: blocking_tcp_echo_client <host> <port>\n";
что-то с индентом

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +    if (argc != 3)
разбор cli-опций через boost program_options

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +    std::cout<<"Ready to recieve reply. Proceed? [y]"; std::cin >> confirm;
- пробелы
- std::cin на другой строке
- есть еще проблемы, но я не буду описывать, ибо это в любом случае надо менять с интерактивного режима на автоматический

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +        if (reply == "Okay, Mr. Client, here's your token...")
это точно хороший способ определять что все ок? подумай, пожалуйста, как сделать это менее костыльно
клиент-то у нас тестовый, а вот сервер уже боевой, и нужно чтобы он как-то более корректно уведомлял о том что все ок

2021-03-11 21:20 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +            in_buf.erase(0,n);
пробел

2021-03-12 19:10 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            std::string in_buf_, out_buf_;
done

2021-03-13 09:31 UTC, tyyu3 commented on src/server/auth/CMakeLists.txt
> +add_executable(melon-auth-test-client
done

2021-03-13 09:50 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +#include <boost/multiprecision/cpp_int.hpp>
Последний не нужен, убрал

2021-03-13 09:51 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                    stream_.expires_after(time_limit_);
done

2021-03-13 15:25 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +            in_buf.erase(0,n);
done

2021-03-15 23:28 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        if (argc<2||argc>3)
done

2021-03-16 00:03 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                bl::expressions::stream
Вынес настройку в core
N.B. Теперь core зависит от lebedev-utils. Альтернативный вариант: просто скопировать пару строк из ce::utils (определение ce::remote), но будет дублирование кода

2021-03-16 00:07 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        ce::ba::io_context ctx{int(threads)};
Никаких особых причин, заменил на нормальный namespace ba = boost::asio

2021-03-16 00:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        for(unsigned i=1;i<threads;++i)
done

2021-03-16 00:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +catch(...){
done

2021-03-16 00:10 UTC, tyyu3 commented on src/server/auth/src/test.cpp
> +    assert(selected_mechanism == wanted_mechanism);
test.cpp уже не нужен, убираю

2021-03-16 00:10 UTC, tyyu3 commented on src/server/auth/src/test.cpp
> +    msa::Credentials credentials = { .username = "john", .password = "doe" };
test.cpp уже не нужен, убираю

2021-03-16 00:11 UTC, tyyu3 commented on src/server/auth/src/test.cpp
> +    [[maybe_unused]] int x = msa::a();
test.cpp уже не нужен, убираю

2021-03-16 00:11 UTC, tyyu3 commented on src/server/auth/src/test.cpp
> +
test.cpp уже не нужен, убираю

2021-03-16 00:14 UTC, tyyu3 commented on src/server/auth/src/test.cpp
> +#include <sasl_wrapper.hpp>
он не нужен, убираю

2021-03-16 00:15 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +      std::cerr << "Usage: blocking_tcp_echo_client <host> <port>\n";
Подправилпоправил

2021-03-16 00:16 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +        if (reply == "Okay, Mr. Client, here's your token...")
Что может быть менее костыльным чем строка определенного вида? Менее костыльна лишь непосредственно функциональнсоть

2021-03-16 00:18 UTC, tyyu3 commented
Глобально я не уверен насколько сейчас имеет смысл переписывать как либо test-client если он
а) нужен только мне и может быть каким мне хочется (разве нет?)
б) будет переделан в автотест

2021-03-16 00:19 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    if (argc != 3)
см. мой коммент

2021-03-16 00:19 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    std::cout<<"Ready to recieve reply. Proceed? [y]"; std::cin >> confirm;
см. мой коммент

2021-03-16 00:20 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +namespace ce
Я не понял, что нужно сделать с main.cpp по этому поводу

2021-03-20 11:28 UTC, kovdan01 requested changes

2021-03-20 11:28 UTC, kovdan01 commented on src/core/include/melon/core/log_configuration.hpp
> +    static void setup_boost_log()
1. у нас не приняты инденты внутри неймспейсов
2. если хочешь это поместить внутрь какого-то кастомного неймспейса - предлагаю неймспейс назвать melon::core::log, а функцию просто setup
3. почему static, что это здесь означает? по-моему если функция определена в хедере, она должна быть инлайн, разве нет? ну и тогда, к слову, неплохо бы еще и в ipp вынести...
4. в любом случае, я не думаю что это должно быть inline, это не что-то очень тривиальное, так что давай в полноценный cpp

2021-03-20 11:28 UTC, kovdan01 commented on src/core/include/melon/core/log_configuration.hpp
> +        bl::add_console_log(std::cerr, bl::keywords::format = (bl::expressions::stream
думаю, тут лучше что-то типа такого (оно занимает довольно много места по горизонтали, но имхо тут зато совершенно очевидная вложенность и иерархия и читаемость)
```
        bl::add_console_log(std::cerr,
                            bl::keywords::format = 
                            (
                                bl::expressions::stream
                                << bl::expressions::format_date_time<boost::posix_time::ptime>("TimeStamp", "%Y-%m-%d %H:%M:%S.%f")  // -V747
                                << " [" << bl::trivial::severity << "] T"
                                << bl::expressions::attr<bl::attributes::current_thread_id::value_type>("ThreadID")
                                << " @" << ce::remote
                                << " : " << bl::expressions::smessage
                            ),
                            bl::keywords::auto_flush = true);
```

2021-03-20 11:28 UTC, kovdan01 commented on src/core/include/melon/core/sasl_client_wrapper.hpp
> +#endif // MELON_CORE_SASL_CLIENT_WRAPPER_HPP_
пробела перед // не хватает

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/CMakeLists.txt
> +    target_link_libraries(melon-auth-test-client PRIVATE ws2_32 mswsock)
тебе это нужно? вроде ведь палсановские ce::asio_utils уже должны их притащить

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +#include <ce/charconv.hpp>
еще разок: тебе _**реально**_ нужны все эти хедеры из ce и буста?

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +using tcp_stream = bb::basic_stream<ba::ip::tcp,
```
using tcp_stream = bb::basic_stream<ba::ip::tcp,
                                    socket_executor_t,
                                    bb::simple_rate_policy>;
```

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            if(m_out_buf[m_out_buf.size()-1] != '\n')
`if (`, `.size() - 1`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                    if(m_out_buf[m_out_buf.size()-1] != '\n')
`if (`, `.size() - 1`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                else
в ифе есть фигурные скобки - значит, и в else ставим

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        }, {}, ba::bind_executor(this->cont_executor(), [](std::exception_ptr e)  // NOLINT
пустой // NOLINT?

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                m_out_buf += "\n";
а зачем нам эти фокусы с \n? это сасль так работает? почему нельзя принять ответ в том виде, в котором он есть, зачем обязательно иметь в конце перевод строки?

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +    }
давай добавим пустую строку перед private

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        std::string x = m_in_buf.substr(0, n-1);
`n - 1`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        std::optional<std::uint16_t> port;
а почему optional, а не просто std::uint16_t? это требование буста? просто я такого не припоминаю
у тебя же порт это обязательный positional параметр, так?

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            ("threads", po::value<unsigned>(),"number of threads to use");
`unsigned>(), "number`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            if (!port||!*port)
1. куда делись все пробелы?
2. это такая извращенная форма проверить, что либо это nullopt, либо там лежит 0? прямо ужас, почему нельзя как-то типа `if (port == std::nullopt || port.value() == 0)`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            if (vm.count("threads"))
у тебя пошла какая-то стейт-машина тут с ифами друг в друге
если так мучаешься с positional параметрами, может обычные именованные использовать?
уж на них-то точно миллиард моих примеров есть

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                std::optional<unsigned> t = vm["threads"].as<unsigned>();
все аналогично порту

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                threads = std::thread::hardware_concurrency();
если в ифе есть фигурные скобки - в else тоже надо ставить

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        for (unsigned i=1; i<threads; ++i)
1. внутри хоть и один операнд, но он не однострочник, поэтому фигурные скобки давай поставим
2. опять же пробелы: `i = 1; i < threads`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +        if (reply == "Okay, Mr. Client, here's your token...")
как минимум нужно эту строчку куда-то вынести и поименовать, а не таскать как литерал за собой

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +    in_buf.erase(0,n);
`0, n`

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +
лишняя пустая строка

2021-03-20 11:28 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +try
а куда делся индент? и точно ли нам нужен try catch? я почти уверен, что catch2 сам навесит поимку исключений и будет  фейлить тесты, если исключения выбросятся

2021-03-20 15:52 UTC, tyyu3 commented on src/core/include/melon/core/log_configuration.hpp
> +        bl::add_console_log(std::cerr, bl::keywords::format = (bl::expressions::stream
Согласен, done

2021-03-20 15:55 UTC, tyyu3 commented on src/core/include/melon/core/sasl_client_wrapper.hpp
> +#endif // MELON_CORE_SASL_CLIENT_WRAPPER_HPP_
done

2021-03-20 15:58 UTC, tyyu3 commented on src/server/auth/CMakeLists.txt
> +    target_link_libraries(melon-auth-test-client PRIVATE ws2_32 mswsock)
ce::asio_utils не линкуется с тестовым клентом, заменил имя на переменную

2021-03-20 16:48 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +#include <ce/charconv.hpp>
Нет

2021-03-20 16:49 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +using tcp_stream = bb::basic_stream<ba::ip::tcp,
done

2021-03-20 16:51 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            if(m_out_buf[m_out_buf.size()-1] != '\n')
done

2021-03-20 16:51 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                    if(m_out_buf[m_out_buf.size()-1] != '\n')
done

2021-03-20 16:54 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                else
done

2021-03-20 17:06 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +try
Не нужен, try-catch зыбыл убрал.

Инденты вернул

2021-03-20 17:07 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +
done

2021-03-20 17:07 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    in_buf.erase(0,n);
done

2021-03-20 17:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        for (unsigned i=1; i<threads; ++i)
done

2021-03-20 17:09 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                threads = std::thread::hardware_concurrency();
done

2021-03-20 17:14 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        std::string x = m_in_buf.substr(0, n-1);
done

2021-03-20 17:14 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +    }
done

2021-03-20 17:16 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                m_out_buf += "\n";
Аналогично примеру палсана, я использую read_until с '\n' в качестве маркера конца сообщения.

2021-03-20 17:17 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        }, {}, ba::bind_executor(this->cont_executor(), [](std::exception_ptr e)  // NOLINT
done

2021-03-20 18:18 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                m_out_buf += "\n";
хорошо, пусть будет пока так
не очень мне это нравится, так что когда будет AMPI - переделаем на сериализацию бинарных буферов через него
там очевидно будет просто размер данных + буфер, но ручками делать это не хочется, пусть это сделает за нас AMPI

2021-03-20 19:30 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            ("threads", po::value<unsigned>(),"number of threads to use");
Разделил табуляциями, как у тебя

2021-03-20 19:35 UTC, tyyu3 commented on src/core/include/melon/core/log_configuration.hpp
> +    static void setup_boost_log()
done

2021-03-20 19:58 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        std::optional<std::uint16_t> port;
Не нужны

2021-03-20 20:00 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            if (!port||!*port)
вообще убрал эту конструкцию

2021-03-20 20:00 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            if (vm.count("threads"))
вообще убрал эту конструкцию

2021-03-20 20:00 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                std::optional<unsigned> t = vm["threads"].as<unsigned>();
Done

2021-03-23 08:10 UTC, kovdan01 requested changes

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +            bae::execute(tp.get_executor(), [&]{
1. тебе нужен только ctx? тогда зачем захватывать все через &, можно только &ctx
2.  Либо фигурную скобку на новую срточку:
   ```
            bae::execute(tp.get_executor(), [&]
            {
                ctx.run();
            });
   ```
   Либо тут вообще в одну строчку адекватно все можно:
   ```
            bae::execute(tp.get_executor(), [&]{ ctx.run(); });
   ```

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +const std::string TOKEN_CONFIRMATION_STRING = "Okay, Mr. Client, here's your token...";
у тебя эта строчка в двух cpp-шниках определена, толку с такого именования почти ноль
нужно это вынести в общее место и оттуда уже использовать

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        std::string x = m_in_buf.substr(0, n-1);
не вижу

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +                if (ec!=boost::asio::error::eof)
`if (ec != boost::asio::error::eof)`

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/main.cpp
> +        ba::static_thread_pool tp{threads-1};
`threads-1`

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +    in_buf.erase(0, n);
а в чем сакральный смысл принимать по не-конст ссылке и потом делать erase?

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +    n = boost::asio::read_until(s, boost::asio::dynamic_string_buffer{in_buf, BUFFER_LIMIT},'\n');
`BUFFER_LIMIT}, '\n'`

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +        size_t n = boost::asio::read_until(s, boost::asio::dynamic_string_buffer{in_buf, BUFFER_LIMIT},'\n');
1. `std::size_t`
2. `BUFFER_LIMIT}, '\n'`

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +        boost::asio::write(s, boost::asio::buffer(to_send + '\n', to_send.size() +1));
`size() + 1`

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +    std::string x = in_buf.substr(0, n - 1);
а зачем тебе откусывать последний символ? типа это `'\n'`? мб есть смысл использовать `std::string_view`?

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +   std::string res;
тело функции можно значительно укоротить, не потеряв (на мой взгляд) в читаемости:

```
if (counter == 0)
    return conn.start(serv_response).response;
return conn.step(serv_response).response;
```

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +std::string get_cli_response(const std::string& serv_response, melon::core::auth::SaslClientConnection& conn, int counter)
вроде мы не скупимся на буквы, поэтому, думаю, server_response лучше, чем serv_response
а вот где подсократить можно - так это в melon::core::auth, создав соответствующий алиас

2021-03-23 08:10 UTC, kovdan01 commented on src/server/auth/src/test_client.cpp
> +        if (counter == 0)
выглядит совсем странно - функцию `get_cli_response` ты не используешь ни разу, и занимаешься здесь проверками как в ней

2021-04-01 14:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +            bae::execute(tp.get_executor(), [&]{
2 вариант, захватываю только ctx

2021-04-02 07:48 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +        if (counter == 0)
Правда, совсем про нее забыл

2021-04-02 08:05 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +std::string get_cli_response(const std::string& serv_response, melon::core::auth::SaslClientConnection& conn, int counter)
Сделал, get_cli_response тоже переименовал в get_client_response, вынес namspace mca в глобальную область видимости

2021-04-02 08:07 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +   std::string res;
Отличная мысль исправил

2021-04-02 08:08 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +                if (ec!=boost::asio::error::eof)
done

2021-04-02 08:09 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +        ba::static_thread_pool tp{threads-1};
добавил пробелы

2021-04-02 08:10 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    n = boost::asio::read_until(s, boost::asio::dynamic_string_buffer{in_buf, BUFFER_LIMIT},'\n');
done

2021-04-02 08:12 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +        size_t n = boost::asio::read_until(s, boost::asio::dynamic_string_buffer{in_buf, BUFFER_LIMIT},'\n');
done

2021-04-02 08:14 UTC, tyyu3 commented on src/server/auth/src/main.cpp
> +const std::string TOKEN_CONFIRMATION_STRING = "Okay, Mr. Client, here's your token...";
перенес в sasl_client_wrapper

2021-04-02 08:23 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +        boost::asio::write(s, boost::asio::buffer(to_send + '\n', to_send.size() +1));
done

2021-04-02 08:30 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    in_buf.erase(0, n);
нету, убрал

2021-04-02 08:54 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    std::string x = in_buf.substr(0, n - 1);
да это '\n'
а как тут std::string_view?

2021-04-02 13:16 UTC, tyyu3 commented on src/server/auth/src/test_client.cpp
> +    std::string x = in_buf.substr(0, n - 1);
done

2021-04-11 21:51 UTC, kovdan01 approved these changes

2021-04-11 21:51 UTC, merged