Add classes to support improved sql dump
kovdan01/melon pull request #95
Opened 2021-03-06 19:01 UTC by h3ll0kitt1

2021-03-07 12:52 UTC, kovdan01 requested changes

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> + * 5. make arrayy of users in chat
5, 13, что все это значит? ну и array, одна y

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +//std::uint64_t find_domain_id(sqlpp::mysql::connection& db, std::string searched_hostname);
если не нужна - удали, пожалуйста

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +std::uint64_t get_domain(sqlpp::mysql::connection& db, const std::string& searched_hostname);
имхо лучше назвать get_domain_id_by_hostname

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +#include <sqlpp11/insert.h>
давай эти инклуды по алфавиту

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void count_users(sqlpp::mysql::connection& db)
зачем нужна эта функция? я не понял

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
>  #include <iostream>
выглядит лишним, используется только в одной функции, и у меня к ней вопросы (см. count_users)

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    db(insert_into(G_DOMAINS).set(G_DOMAINS.hostname = searched_hostname));
а во что выставляется external?

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    if(!result.empty())
`if (`

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    auto result = db(select(G_DOMAINS.domainId).from(G_DOMAINS).where(G_DOMAINS.hostname == searched_hostname));
а что скрывается за auto? почему не нормальный тип?

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +       return  row.domainId;
лишний пробел после return

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    return 0;
возвращать 0, если не нашли такой домен - странновато, особенно с учетом того, что 0 - вполне валидный domain_id
верни -1 или используй в качестве возвращаемого значения std::optional
имхо вариант с -1 лучше, т.к. проще, просто заведи себе где-нибудь константу `INVALID_ID = std::uint64_t(-1);`

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    if (domainid != 0)
после фикса функции get_domain здесь нужно изменить логику

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +
в этом и других местах убери миллиард пустых строк, пожалуйста
обычно нужна одна, где-то между разными по смыслу блоками кода можно две

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void add_domain(sqlpp::mysql::connection& db, const std::string& searched_hostname)
почему searched_hostname? мы же его не ищем

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    db(insert_into(G_DOMAINS).set(G_DOMAINS.hostname = domain.hostname()));
а почему external не выставляем?

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +//now you cannot, should think what i should delete or not from db
я совершенно не понял этот комментарий + после // нужен пробел

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +       std::cout << "Number of users : " <<  row.count << std::endl;
куда-то отступ поехал, 3 пробела вместо 4
так или иначе, эта функция вообще выглядит ненужной

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +// List of all users in database
давай для единообразия все комментарии либо с заглавной буквы начинать, либо со строчной
предлагаю с заглавной, чтобы можно было писать больше, чем одну фразу, в формате нескольких предложений

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void add_user(sqlpp::mysql::connection& db, const melon::core::User& user, const std::string& searched_hostname)
опять же почему searched?

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    std::uint64_t domainid = get_domain(db, searched_hostname);
в других местах ты пишешь domain_id, давай и здесь так

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    db(insert_into(G_USERS).set(G_USERS.username = user.username(), G_USERS.domainId = domain_id,  G_USERS.status = static_cast<std::uint8_t>(melon::core::User::Status::OFFLINE)));
`= domain_id,  G_USERS.status` - два пробела после запятой, нужен один

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
>          online_users.emplace_back(std::move(user));
можно даже не создавать объект user, а сразу передать аргументы конструктора в emplace_back, и он создастся на месте

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void count_number_recieved_messages (sqlpp::mysql::connection& db)
1. нужно убрать лишний пробел: `void count_number_recieved_messages(sqlpp::mysql::connection& db)`
2. опять же, зачем эта функция? по аналогии с count_users

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +       std::cout << "Number of messagers : " <<  row.count << std::endl;
опять пробелы...

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
А что если принять new_text по значению, а в 174 строке сделать std::move? если скомпилируется и не будет ворнингов стат. анализа, то это предпочтительнее, т.к. тогда будет опция "подарить" извне строчку (сделать std::move извне, получится два мува, но ни одного копирования; в текущем варианте всегда ровно 1 копирование)

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
думаю, лучше назвать функцию update_message_text, и порядок аргументов поменять: сначала messasge, потом new_text (имхо логичнее)

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void update_status_for_seen(sqlpp::mysql::connection& db, const melon::core::Message& message)
я думаю лучше сделать функцию update_message_status, в которую просто передавать нужный статус

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void add_chat(sqlpp::mysql::connection& db, const melon::core::Chat& chat, const std::string& searched_hostname)
почему searched...

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +//deletes chat -> deletes messages from chat, all info in Chats_Users concearnig this chat
пробел

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
>          messages_in_chat.emplace_back(std::move(message));
аналогично, можно сразу передать в emplace_back аргументы конструктора, не создавая объект message вообще

2021-03-07 12:52 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void update_chatname(sqlpp::mysql::connection& db, const std::string& new_chatname, const melon::core::Chat& chat)
опять же имхо лучше сначала chat, потом new_chatname

2021-03-07 14:14 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +    auto result = db(select(G_DOMAINS.domainId).from(G_DOMAINS).where(G_DOMAINS.hostname == searched_hostname));
![image](https://user-images.githubusercontent.com/52863098/110242757-8afb8d80-7f68-11eb-880c-21adbdd0ed0f.png)
 
Потому что так было написано автором sqlpp11 в своей wiki

2021-03-07 14:56 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
Я не оч уверена в аргументах функций, я нигде не апдейчу сам message, когда их передаю, просто напрямую изменяю в базе данных. Мне как лучше с ним поступать? В этой функции сразу и ему менять значение поля?

2021-03-07 14:57 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
Или надо было поменять в message значение text на новое и уже просто его передавать?

2021-03-07 14:59 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    auto result = db(select(G_DOMAINS.domainId).from(G_DOMAINS).where(G_DOMAINS.hostname == searched_hostname));
Окей, хорошо

2021-03-07 15:01 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
Вообще эта функция напрашивается как функция-член класса, а не свободная
Т.е. в Message делаешь setter:
```
void update_text(sqlpp::mysql::connection& db, std::string new_text)
{
    // обновление в БД
    // обновление поля m_text в классе
}
```

2021-03-07 15:02 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
Connection, чтобы каждый раз не передавать, можно в конструкторе принять; он ведь не меняется с течением времени?

2021-03-07 15:04 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +void update_text(sqlpp::mysql::connection& db, const std::string& new_text, const melon::core::Message& message)
Нет, не меняется

2021-03-08 16:39 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +void count_users(sqlpp::mysql::connection& db)
убрала

2021-03-08 16:39 UTC, h3ll0kitt1 commented on src/server/storage/include/storage.hpp
> +std::uint64_t get_domain(sqlpp::mysql::connection& db, const std::string& searched_hostname);
исправила

2021-03-08 16:41 UTC, kovdan01 requested changes

2021-03-08 16:41 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +//std::uint64_t INVALID_ID = std::uint64_t(-1);
а почему закоменчено?

2021-03-08 16:41 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +    Message(sqlpp::mysql::connection& db, std::uint64_t message_id, std::uint64_t domain_id,std::uint64_t user_id,
Пробел `domain_id, std::uint64_t`

2021-03-08 16:41 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +         : melon::core::Message(message_id, domain_id, user_id, chat_id, text, status), m_db(db)
Реализацию надо вынести в ipp

2021-03-08 16:41 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +    sqlpp::mysql::connection& m_db;
это явно должен быть приватный член данных

2021-03-08 16:41 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +
пустая строка лишняя

2021-03-08 16:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void update_text(const std::string& new_text)
Реализацию надо вынести в ipp

2021-03-11 21:43 UTC, kovdan01 requested changes

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_domain_id(std::uint64_t new_domain_id);
по-моему не должно быть ситуации, когда надо менять domain_id, это primary key

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void remove_domain();
1) в core эта функция не нужна имхо (что тут удалять? удаляем мы из БД, эта функция нужна только в классе-наследнике)
2) просто remove

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void change_status(Status new_status);
set для единообразия

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_domain_id(std::uint64_t new_domain_id);
аналогично классу domain - выглядит лишним

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_user_id(std::uint64_t new_user_id);
аналогично

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void update_text(const std::string& new_text);
1) set для единообразия
2) принимаем по значению, делаем std::move

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void remove_message();
remove

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void remove_user();
remove

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_message_id(std::uint64_t new_message_id);
все аналогично с другими классами - имхо лишнее

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +//    virtual void update_chatname(const std::string& new_chatname)
если лишнее - надо удалить

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    virtual void remove_chat();
remove

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_chat_id(std::uint64_t new_chat_id);
см. аналогично другим классам

2021-03-11 21:43 UTC, kovdan01 commented on src/core/src/storage_class.cpp
> +void Domain::remove_domain()
функции вроде сделаны, а делать ничего не делают

2021-03-11 21:43 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.ipp
> +inline void Chat::set_chat_id(std::uint64_t new_chat_id)
в таких местах можно и без префикса new_ - и так понятно

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +    User(sqlpp::mysql::connection& db, std::uint64_t user_id, std::uint64_t domain_id, std::string username, Status status);
много параметров, давай на 2 строки

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +    User(sqlpp::mysql::connection& db, std::uint64_t user_id, std::uint64_t domain_id, std::string username, Status status, const std::string& hostname);
аналогично

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +//    mss::User user2(db, 0, 0, "kitt1", mc::User::Status::ONLINE, "not_in_list_domain");
если лишнее - нужно удалить

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +                                   G_MESSAGES.timesend = std::chrono::system_clock::now(),
не хватает двух пробелов в этих и следующих строках - G_MESSAGES должны быть выровнены по предыдущей строке

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +                                   G_MESSAGES.timesend = std::chrono::system_clock::now(),
аналогично

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +     : melon::core::Message(message_id, domain_id, user_id, chat_id, std::move(text), status), m_db(db)
давай `, m_db(db)` на другую строку

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +     : melon::core::Message(message_id, domain_id, user_id, chat_id, std::move(text), status), m_db(db)
давай `, m_db(db)` на другую строку

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +        std::cout << "timesend is " << row.timesend << "\n";
вывод на экран... это вообще нужно?
что-либо из iostream смотрится очень лишним

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +//        const auto tp = std::chrono::system_clock::time_point{row.timesend.value()};
если не нужно - давай удалим

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    : melon::core::Chat(chat_id, domain_id, std::move(chatname)), m_db(db)
давай `, m_db(db)` на другую строку

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +//void Chat::update_chatname(const std::string& new_chatname)
если не нужно - давай удалим

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +//Deletes chat: deletes messages from chat, all info in Chats_Users concearnig this chat
пробел после //

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +                                G_USERS.status = static_cast<int>(this->status())));
два пробела

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    //m_db(update(G_USERS).set(G_USERS.status = static_cast<int>(new_status)).where(G_USERS.userId == this->user_id()));
если лишнее - давай удалим

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    //throw INVALID_ID; ?
уж точно не throw INVALID_ID (выброс числа в качестве исключения - так себе идея)
можно было бы выбрасывать какое-нибудь исключение, но, думаю, лучше не надо, т.к. тут исключения выглядят как обычная ситуация, а не редкая, и их выбрасывание будет накладно по ресурсам

2021-03-11 21:43 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +                                                                   std::uint64_t domain_id, std::uint64_t user_id)
в отступе один лишний пробел

2021-03-19 21:47 UTC, h3ll0kitt1 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_domain_id(std::uint64_t new_domain_id);
сделала protected как обсуждали во вт

2021-03-19 21:48 UTC, h3ll0kitt1 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_domain_id(std::uint64_t new_domain_id);
тоже protected

2021-03-20 10:48 UTC, kovdan01 requested changes

2021-03-20 10:48 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    Message(std::uint64_t message_id, std::uint64_t domain_id, std::uint64_t user_id, std::uint64_t chat_id, std::string text, Status status);
Давай классы Chat и Message поменяем местами, чтобы оно шло как бы по убыванию размера сущности
Чисто сами классы, чтобы было так

```
class Chat
{
    // ...
};
class Message
{
    // ...
};
```

2021-03-20 10:48 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    [[nodiscard]] std::chrono::system_clock timestamp() const;
а куда делся time_point?

2021-03-20 10:48 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    inline void set_timestamp(std::chrono::system_clock new_timestamp);
тут явно опять же time_point не хватает + во всех таких местах имхо префикс new_ не нужен, и так понятно все

2021-03-20 10:48 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +    std::chrono::system_clock m_timestamp;
опять time_point пропал

2021-03-20 10:48 UTC, kovdan01 commented on src/core/src/storage_class.cpp
> +void Domain::set_external(bool new_external)
это явно можно inline и в ipp вместо cpp

2021-03-20 10:48 UTC, kovdan01 commented on src/core/src/storage_class.cpp
> +void User::set_status(Status new_status)
аналогично здесь и в других тривиальных сеттерах

2021-03-20 10:48 UTC, kovdan01 commented on src/core/include/melon/core/storage_class.hpp
> +
лишняя пустая строка

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +const std::uint64_t INVALID = 0;
что такое просто INVALID?

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +const std::uint64_t INVALID_ID = std::uint64_t(-1);
думаю, это вполне можно в хедер, чтобы было доступно откуда угодно, и тогда придется добавить слово inline

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    std::uint64_t this_domain_id = max_domain_id(m_db);
по-хорошему неплохо бы найти нормальный способ получить последний вставленный id, типа https://stackoverflow.com/questions/9477502/get-the-last-inserted-row-id-with-sql-statement
если не можешь найти - временно забей

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +     : melon::core::Domain(INVALID, std::move(hostname), false)
почему INVALID, а не INVALID_ID?

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +                     .from(G_MESSAGES).where(G_MESSAGES.chatId == this->chat_id() and G_MESSAGES.domainId == this->domain_id()
какой-то микс стилей у нас, то &&, то and, давай уж &&
и предлагаю по одному условию на строке, типа:
```
.from(G_MESSAGES).where(G_MESSAGES.chatId == this->chat_id() &&
                        G_MESSAGES.domainId == this->domain_id() &&
                        G_MESSAGES.messageId == this->message_id()));
```

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +     : melon::core::Message(message_id, domain_id, INVALID, chat_id, "", Message::Status::FAIL)
В СЛЕДУЮЩИЙ PR

в melon::core для соответствующих классов надо тоже написать несколько разных видов конструкторов, чтобы здесь не мучиться так
т.е. конструктор для селекта (только PK, в данном случае message_id, chat_id, domain_id), и контсруктор для инсерта (без id, но со всем остальным, в данном случае chat_id, domain_id, status, text и что там еще может быть, все кроме message_id)
тогда здесь не придется колхозить инвалидные значения, а можно будет вызвать соответствующий конструктор
два вида конструкторов энивей понадобятся - скажем, клиенты аналогичным образом смогут захотеть либо создать сообщение (аналог инсерт - отправить на сервер), либо просто сделать экземпляр класса, соответствующий уже созданному сообщению (аналог селекта, типа запрос на сервер - дай пожалуйста мне список сообщений)

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +        // check format again
если не нужно - давай удалим

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +        throw std::runtime_error("No message in database");
давай сделаем отдельный тип исключения для этого
что-нибудь типа
```
class IdNotFoundException : public std::runtime_error
{
public:
    using std::runtime_error::runtime_error;
    using std::runtime_error::operator=();
};
```
и потом можно будет ловить его таргетированно

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    auto result =  db(select(max(G_MESSAGES.messageId)).from(G_MESSAGES).unconditionally());
лишний пробел после =

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +//std::uint64_t get_domain_id_by_hostname(sqlpp::mysql::connection& db, const std::string& hostname)
если не нужно - давай удалим

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    for (const auto& row : db(select(all_of(G_CHATS))
тут сложно придумать нормальное форматирование, но думаю текущее точно нужно поменять, уж слишком непонятно
можно, например, так (но можно и лучше придумать):
```
for (const auto& row : db(select(all_of(G_CHATS)).from
                         (
                             G_CHATSUSERS.join(G_CHATS).on
                             (
                                 G_CHATSUSERS.chatId == G_CHATS.chatId &&
                                 G_CHATSUSERS.domainId == G_CHATS.domainId
                             )
                         ).where(G_CHATSUSERS.userId == user.user_id())
                         )
    )
    {
        chats_for_user.emplace_back(row.chatId, row.domainId, row.chatname);
    }
```

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +    for (const auto& row : db(select(all_of(G_USERS))
здесь тоже явно нужно что-то придумать с форматированием

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +// Should do it member for Chat ?
В СЛЕДУЮЩИЙ PR

да, это конечно выглядит как что-то для мембера
более того, я вижу это так: в базовом классе в melon::core делается чисто виртуальная функция
```
virtual std::vector<std::unique_ptr<melon::core::Message>> get_blablabla() = 0;
```
unique_ptr - потому что указатели на наследников умеют преобразовываться в указателей на родителей (таким образом у наследников интерфейс не изменится)
не сырой указатель - для автоматизации владения
не ссылка - т.к. нельзя сделать вектор ссылок
далее наследники (в частности, melon::server::Message переопределят эту функцию для себя

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +// Should do it member for Chat ?
В СЛЕДУЮЩИЙ PR

конкретика - в аналогичном коменте ниже

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/storage.cpp
> +// Should do it also member for User ?
В СЛЕДУЮЩИЙ PR

конкретика - в аналогичном коменте ниже

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    //    mss::User user3(db, domain_edward.domain_id(), "anna", mc::User::Status::ONLINE);
если не нужно - давай удалим

2021-03-20 10:48 UTC, kovdan01 commented on src/server/storage/src/main.cpp
> +    // Domains
В СЛЕДУЮЩИЙ PR

я так понимаю, это условно тестовые запросы, которыми ты проверяешь работоспособность своего кода
нужно написать авто-тесты на catch2

2021-03-20 10:53 UTC, kovdan01 requested changes

2021-03-20 10:53 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +    Message(sqlpp::mysql::connection& db, std::uint64_t domain_id, std::uint64_t user_id, std::uint64_t chat_id,
давай более последовательно: сначала то, что относится к идентификации самого сообщения (т.е. домен и чат), потом уже его свойства (юзер, текст и тд)

2021-03-20 10:53 UTC, kovdan01 commented on src/server/storage/include/storage.hpp
> +    Message(sqlpp::mysql::connection& db, std::uint64_t message_id, std::uint64_t domain_id, std::uint64_t chat_id);
опять же давай более последовательно: либо message, chat, domain, либо domain, message, chat (думаю, первый вариант лучше)
а то ты сейчас как американцы со своими ММ-ДД-ГГГГ

2021-03-20 11:00 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +    std::uint64_t this_domain_id = max_domain_id(m_db);
В sqlpp11 для mysql нет last_insert функции, есть только для sqlite3

2021-03-20 11:03 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +const std::uint64_t INVALID = 0;
Автоинкремент же начинается с 1, но при этом если я поставлю как инвалид домен INVALID_ID - он будет мне возвращаться всегда как максимальный id, а у меня зависят функции от этого - max_user_id, ... и тд. Поэтому я думала поменять INVALID_ID на равный 0

2021-03-20 18:02 UTC, h3ll0kitt1 commented on src/server/storage/src/main.cpp
> +    // Domains
Добавила в issue

2021-03-20 18:18 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +     : melon::core::Message(message_id, domain_id, INVALID, chat_id, "", Message::Status::FAIL)
добавила issue

2021-03-20 18:19 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +// Should do it member for Chat ?
добавила issue

2021-03-20 18:19 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +// Should do it member for Chat ?
добавила issue

2021-03-20 18:19 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +// Should do it also member for User ?
добавила в issue

2021-03-20 18:44 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +const std::uint64_t INVALID = 0;
вернула const std::uint64_t INVALID_ID = std::uint64_t(-1),  удалила INVALID

2021-03-20 18:46 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +     : melon::core::Domain(INVALID, std::move(hostname), false)
исправила

2021-03-20 19:44 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +    for (const auto& row : db(select(all_of(G_CHATS))
я пока не придумала, что-то классное, сделала такую же

2021-03-23 08:51 UTC, h3ll0kitt1 commented on src/core/src/storage_class.cpp
> +void Domain::set_external(bool new_external)
добавила

2021-03-23 10:50 UTC, h3ll0kitt1 commented on src/server/storage/src/storage.cpp
> +        throw std::runtime_error("No message in database");
Добавила в storage.hpp

2021-03-23 11:53 UTC, kovdan01 approved these changes

2021-03-23 11:53 UTC, merged